### ISSUE TITLE
Configurable InitialContext

### ISSUE THREAD

**Issue by ghost** [Activiti/Activiti#117]
ProcessEngineConfigurationImpl.initDataSource() resolves datasource from default initialcontext. It will be nice if initialcontext is configurable.

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
