### ISSUE TITLE
API changes review for Activiti Engine

### ISSUE THREAD

**Issue by lvc** [Activiti/Activiti#1384]
The review of API changes for the Activiti Engine library since 5.17.0 version: https://abi-laboratory.pro/java/tracker/timeline/activiti-engine/

The report is updated three times a week. Hope it will be helpful for users and maintainers of the library.

The report is generated by https://github.com/lvc/japi-tracker

Thank you.

![activiti-1](https://user-images.githubusercontent.com/1517837/29175302-b6e7f614-7df9-11e7-8b63-c420a5706ace.png)
![activiti-2](https://user-images.githubusercontent.com/1517837/29175307-bb594a22-7df9-11e7-84f5-b0476045801b.png)

**Comment by Salaboy** [comment]
@lvc this is great. We are going to start versioning and managing the project public APIs with clear deprecation policies. I'm looking forward to see how this improves in the next couple of years.

**Comment by lvc** [comment]
@Salaboy,

I'll enable daily analysis of snapshots if you'll publish them somewhere (e.g. here https://oss.sonatype.org/content/repositories/snapshots/org/activiti/activiti-engine/).

Also please let me know if some other activiti-* modules should be added to the tracker.

Thank you.

**Comment by ryandawsonuk** [comment]
The snapshot link is https://maven.alfresco.com/nexus/content/repositories/activiti-snapshots/org/activiti/activiti-engine/

But I don't think you need to do this on snapshots. We do an EA release each month at the moment. If you could include all the releases rather than just those listed above that would also be interesting. See

https://oss.sonatype.org/#nexus-search;gav~org.activiti~activiti-engine~~~

**Comment by Salaboy** [comment]
@lvc can we create a separate report for Activiti Cloud? we are publishing Early Access Releases every month and it will be good to keep track of this work. We are publishing to maven central: http://search.maven.org/#search%7Cga%7C1%7Cactiviti-cloud 
Not sure how difficult is to set up that for each different artifact.

**Comment by lvc** [comment]
@ryandawsonuk,

> We do an EA release each month at the moment. If you could include all the releases rather than just those listed above that would also be interesting.

Reports for Activiti 7-* have been added here: https://abi-laboratory.pro/java/tracker/timeline/org.activiti.engine/

![activiti-3](https://user-images.githubusercontent.com/1517837/33591967-ae2365b2-d999-11e7-92e5-284aa036ddc6.png)
![activiti-4](https://user-images.githubusercontent.com/1517837/33591971-b1d581fe-d999-11e7-9257-c5b9c181809b.png)

**Comment by lvc** [comment]
@Salaboy,

> can we create a separate report for Activiti Cloud? we are publishing Early Access Releases every month and it will be good to keep track of this work.

I'll add them when at least two releases will be available (I only see one per each artifact currently and so can't plot the report). Please ping me in the comment here on the next release. Thank you.

**Comment by lvc** [comment]
Report for entire Activiti 6: https://abi-laboratory.pro/java/tracker/timeline/activiti/

![activiti-5](https://user-images.githubusercontent.com/1517837/33592257-0d8abad6-d99b-11e7-8f1c-953b67da6db5.png)
![activiti-6](https://user-images.githubusercontent.com/1517837/33592262-106b30aa-d99b-11e7-8685-3c0987b63587.png)

**Comment by Salaboy** [comment]
@lvc this is a very good and useful contribution. For v5 and v6 I don't think that it adds too much or represent something that people can use. Mostly because v5 and v6 contained the web tooling and rest apis inside the same repository. Now that we have spitted the code in a more "mature" way and our release processes are improving we these numbers will make much more sense.
We announced yesterday that version 7-201711-EA was released, so I'm interested to understand a little bit more in detail what the numbers in the report means. For example:  for 7-201710-EA which modules are included? In theory next year, you should be able to only add to the report our -api projects. No need to include the internal implementations that should be just internal. Is the reporting tool evaluating interfaces and implementation classes? Can you elaborate a little bit about what's the processes used come up with those numbers?
