### ISSUE TITLE
@ComponentScan on org.activiti in starters is too broad

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1399]
The audit service in particular has a dependency on the engine in the effective pom. Is it needed? Can it be excluded?

If you look at the JpaApplication in the tests in the starter for audit it does a broad componentscan on org.activiti. If you restrict it just to the audit package then it doesn't work. Need to debug and figure out what packages needed.

**Comment by Salaboy** [comment]
we solved most of this with the new API for Beta1 and the starters refactoring. More refined issue needs to be created with the ones that we want to improve now.

**Comment by igdianov** [comment]
The component scan problem primarily affects how the different modules are discovered and configured in the Spring Boot application context. It causes same beans to accidentally override each other with unpredictable effects, i.e. globally named beans like security, scheduling, datasource, etc. It used to be common practice until SB 2.1 has disabled bean overriding behavior to make people aware of the problems in their software: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#bean-overriding and https://github.com/spring-projects/spring-boot/issues/13609

This problem affects users that reported issues with not being able to disable Spring Security by excluding SpringSecurityAutoConfiguration when using Activiti Spring Boot starter. The component scan is the problem, because it is triggering security configuration classes scan unconditionally with https://github.com/Activiti/Activiti/blob/f92d6d3853db14b46232c9f97f9d04dbd0857f31/activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/EndpointAutoConfiguration.java#L29

We need to remove `@ComponentScan` and extract security configuration from https://github.com/Activiti/Activiti/blob/f92d6d3853db14b46232c9f97f9d04dbd0857f31/activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/MethodSecurityConfig.java#L12 into standalone auto configuration class to apply it conditionally only if Spring Security Starter is on classpath in order to make it flexible for users to trigger and apply security configuration by including Spring Boot Security Starter in their pom.xml or exclude with inline via class or property.

There existing closed issues that dealt before with component scan problem on the surface, but none of them had addressed the root cause of using component scan in Activiti Spring Boot Starter:
https://github.com/Activiti/Activiti/issues?q=is%3Aissue+componentscan+is%3Aclosed

Removing `@ComponentScan` will cause downstream issues in Activiti Cloud project, so will need to comb the code in all repositories to remove remaining component scans and replace them with auto configuration classes provided by each module.
