### ISSUE TITLE
hundreds of connection leak in ExecuteAsyncRunnable.run

### ISSUE THREAD

**Issue by deanwong** [Activiti/Activiti#1453]
HikariCP + eclispeLink 2.6+ mysql 5.7 + activiti 5.22  
I opend  HikariCP's LeakDetectionThreshold and found out lots of connection leaks.

This is the simplest [sample project ](https://github.com/deanwong/activiti-sample
).  Just run IntegrationTest then you can see the leak log in console.

Thanks.

**Comment by deanwong** [comment]
Any comments?

**Comment by daisuke-yoshimoto** [comment]
@deanwong 

I'm sorry for the delay in answering.
But, I think that this event is not a connection leak.

ExecuteAsyncRunnable is a resident thread for executing an asynchronous job, just using the same connection all the time.
Since Hikari CP's judges connection leak as simply occupying connection for the set time or more, it is only logging out the above as a connection leak.

With your implementation this time, if use a connection for more than 2 seconds, it will be detected as a connection leak.

```java
private final static Long LEAK_DETECTION_THRESHOLD = TimeUnit.SECONDS.toMillis(2L);

HikariConfig config = new HikariConfig();
config.setLeakDetectionThreshold(LEAK_DETECTION_THRESHOLD);
```

PS: By the way, I had never used Gradle, so it took me a long time to verify 😢

**Comment by daisuke-yoshimoto** [comment]
@deanwong Any update?
Can I close this issue?

**Comment by Salaboy** [comment]
@deanwong we will close this issue due to inactivity. As @daisuke-yoshimoto mention this is probably not a leak.

**Comment by deanwong** [comment]
@daisuke-yoshimoto  Sorry for the late reply, many thanks for your help.
