### ISSUE TITLE
Different datasources for Activiti and delegates in spring boot starter

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1489]
Spring boot starter just uses standard spring datasource. Should provide a way to have an activiti-specfic one. This is a problem for non-cloud as means any entities in delegates have to be in the same database as Activiti. Can be overridden but it is a bit painful:
https://community.alfresco.com/thread/224893-activiti-with-spring-boot-and-two-datasources
We could build it into the starter to preferentially take a datasource with an ‘activiti’ prefix if available.

**Comment by Salaboy** [comment]
@ryandawsonuk for Activiti Cloud that shoudn't be a problem right? The datasource for the Runtime Bundle should be internal and not used by any delagate or connector. Not sure if we want to provide that secondary datasource alternative, just because you can use Activiti Cloud Connectors to deal with those interactions.

**Comment by Salaboy** [comment]
@ryandawsonuk I would recommend to close this one.

**Comment by ryandawsonuk** [comment]
Yeah this is basically an Activiti 6 issue
