### ISSUE TITLE
Process Definitions are being redeployed with a new version when Runtime Bundle started using the same DB instance.

### ISSUE THREAD

**Issue by Salaboy** [Activiti/Activiti#1527]
We need to review the default behavior for Runtime Bundles that keep the same database instance and redeploy the process defs on bootstraping.

**Comment by cijujoseph** [comment]
There is a filtering capability in the deployment apis to avoid duplicate deployment if the file hasn't changed. https://www.activiti.org/userguide/index.html#_automatic_resource_deployment

**Comment by Salaboy** [comment]
@cijujoseph can you help us to check if this is working as expected in runtime bundles?

**Comment by cijujoseph** [comment]
@Salaboy : I just tested this using the cloud examples the following way and can confirm that the process definitions are **not redeployed**  if it already exists in the database.

- Created a postgres service instead of one local db per runtime bundle
- Stopped the runtime bundles via kube dashboard which forced the creation of another rb instance against the same database. 
- Invoked the get process definition api and verified that the process definition id remained the same.

**Comment by Salaboy** [comment]
@cijujoseph if the runtime bundle fails to start it should be automatically restarted by kubernetes. We need to improve the probes.

**Comment by Salaboy** [comment]
@ffazzini I'm assigning this to you to review and improve.

**Comment by ffazzini** [comment]
@Salaboy If runtime bundle service fails to start, it is automatically restarted by kubernetes already with the probes. What do we have to improve specifically?

**Comment by Salaboy** [comment]
@cijujoseph can you please share with @ffazzini how to reproduce the issue of 2 runtime bundles starting at the same time and one failing to create the DB? that should leave the 2nd one in an inconsistent state, which the probe should understand and restart. After restarting both instances should work.

**Comment by cijujoseph** [comment]
@Salaboy @ffazzini , I produced the issue by starting 2 rb replicas (in the cloud-example project). To be frank I didn't wait that long for it to be restarted by kubernetes, I just killed it from the dashboard which created another node. I'll see if I can reproduce that issue again and check if it gets re-started. Only thing I remember is seeing a 503 error on dashboard.

**Comment by Salaboy** [comment]
@erdemedeiros @ryandawsonuk please check this as well, if you are trying to create 2 replicas this might appear.

**Comment by Salaboy** [comment]
@erdemedeiros @ryandawsonuk it sounds like we already fixed this. Is this assumption correct?

**Comment by ryandawsonuk** [comment]
I've been running multiple replicas of the runtime bundle in the twitter example without seeing this issue. I had it logging number of process executions broken down by process definition so I would've seen if there were multiple process definitions or if one bundle was missing definitions.

**Comment by erdemedeiros** [comment]
@ryandawsonuk If I remember well, this problem happens when you keep the database alive and restart the runtime-bundle only (not the database). And I think that there is actually no errors, there  will be two versions deployed for the same process definition, but you probably can start and execute instances for both versions.

**Comment by erdemedeiros** [comment]
@ryandawsonuk @Salaboy I missed @cijujoseph I'm going to close it.
