### ISSUE TITLE
Swagger client generate - Feign

### ISSUE THREAD

**Issue by ffazzini** [Activiti/Activiti#1554]
### Maven dependencies

```xml
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-feign</artifactId>
      <version>1.3.5.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.security.oauth</groupId>
      <artifactId>spring-security-oauth2</artifactId>
      <version>2.2.0.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-security</artifactId>
      <version>1.2.1.RELEASE</version>
    </dependency>
```

### Maven plugin
```xml
<plugin>
        <groupId>io.swagger</groupId>
        <artifactId>swagger-codegen-maven-plugin</artifactId>
        <version>2.2.3</version>
        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>swagger.json</inputSpec>
              <language>spring</language>
              <library>spring-cloud</library>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

**Comment by Salaboy** [comment]
@ffazzini during the weekend I manage to get the new docker images with the new endpoints and I've managed to create this example project: https://github.com/Activiti/activiti-cloud-examples/tree/feature/salaboy-1554-rb-feign-client

It wasn't working just yet, but I guess it is a good start. I've included the new swagger.json
The objective for this project is to contain a spring boot app that calls the runtime bundle using the Feign generated interfaces, from a test. 

Notice that I haven't used your suggested versions for the spring cloud starter, because we need to be aligned with their spring boot 2 and spring cloud latest snapshots/milestones and not 1.5.x

**Comment by Salaboy** [comment]
@ffazzini please recheck on Jan with latest spring boot and cloud updates.

**Comment by Salaboy** [comment]
@ffazzini any updates on this?

**Comment by ffazzini** [comment]
was not @constantin-ciobotaru looking into this? On my understanding after @erdemedeiros allowed the non-hal API format, this should work just fine.

**Comment by erdemedeiros** [comment]
https://github.com/Activiti/Activiti/issues/1419 is merged now.

**Comment by Salaboy** [comment]
closing this, because I see a PR merged.
