### ISSUE TITLE
How to embed the Activiti workflow in a HTML page?

### ISSUE THREAD

**Issue by hcoderonly** [Activiti/Activiti#1587]
I am able to create the workflows using Java/Spring, but I am unable to find a way to run these workflows in a web environment/html file.
For example: 
1. I want to create a workflow
2. embed the workflow in html 5
3. start the workflow in the html page?

Can someone help me with the above request pls?

**Comment by ryandawsonuk** [comment]
You could use the spring boot starter and add the rest API and make rest calls from the webpage. See https://spring.io/blog/2015/03/08/getting-started-with-activiti-and-spring-boot and http://www.baeldung.com/spring-activiti

**Comment by hcoderonly** [comment]
Thank you @ryandawsonuk.
I can see that you can return the workflow value to the UI, I was wondering if there was a way that the workflow is ran on the website.
For example:
I create  the workflow below using Workflow Editor:
(Start)--->[This is a test workflow]--->(End)

In the html UI, I want to see the workflow run like this:

This is a test workflow
                          [End Button]


Now, do I have to manually create the UI functionality, or there is a way that I can embed it inside my html page?

**Comment by Salaboy** [comment]
@hcoderonly hi there, please use the forums for this type of questions. 
Activiti will always run in the backend (meaning in your services) and you can definitely interact with the UI and send values back to notify the user that the "workflows" are running. You can also start the workflow from the UI and show the workflow diagram, but the workflow itself will never run in the browser. 

I'm closing this issue, because in fact this is not an issue.
