### ISSUE TITLE
6-Beta2 truncated result for ExtensionElement::getElementText

### ISSUE THREAD

**Issue by ggrnd0** [Activiti/Activiti#1635]
In December, 2017 we still use 6-beta2 version...

In last month we found error, for some extensionElement their ExtensionElement::getElementText returns truncated content.

In all common properties is:
 - length 100+ chars. utf-8. only ANSI.
 - wrapped with CDATA or not.
 - 3 nesting level: //bpmnElement/extensionElements/customCollection/customElement/attribute .
inner content of attribute will be truncated.
 - 4 nesting level reads correctly.
 - truncation only begin part of content(COntent -> ntent). ~10-80%. every restart same or different.
 - we have similar processes with identical tag content, but not all truncated.
 - app restarts ans update of java upto 8.151(152) do not affects truncations.
 - enableSafeBpmnXml does not help.

Scenario is fully correct, there in no broken utf surragate pairs, all line end is \n only.
Scenario deployed multiple times has 

We cannot update activiti now. And hope to solve problem with 6-beta2 version if its possible.

Any ideas?

**Comment by balsarori** [comment]
Hi @ggrnd0 

Can you provide some code that we can use to reproduce the issue? And what's blocking you from using the 6.0 release?

**Comment by ggrnd0** [comment]
1. i can-t, it is reproduce very randomly and not handled on small processes...
2. time for migrate. we planned migration at 2018Q2

**Comment by ggrnd0** [comment]
i forgot.
it stable reproduces on debian8 server but not on developer machines...

**Comment by Salaboy** [comment]
@ggrnd0 @balsarori in community we do not fix things for beta release, and in this case where there is a final version already out you should migrate to the latest released version. 
We totally recommend you to test against 6 final and if it doesn't work there you will need to coordinate with us the fix for it. It sounds more like a operating system specific issue with encoding and probably your webserver is involved in the problem as well. @balsarori do you have any idea why truncation might happen in there?

**Comment by balsarori** [comment]
if we can't reproduce then we can't be of much help. If the issue is only reproduced on server but not on developers machines it could be an environment issue.

@ggrnd0 feel free to re-open this if you still this is an issue in Activiti.
