### ISSUE TITLE
have easy way to turn on debug logging in our apps

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1678]
We can easily turn on debug level logging in spring boot by passing in an environment var - just 'debug=true'. See https://github.com/Activiti/activiti-cloud-audit/blob/develop/Dockerfile#L14 . But could we turn on debug logging for our own code in a similar way? One way to do it would be with spring profiles, as we do already with controlling whether logs go to local, to logstash (profile called 'kube') or both - see https://github.com/Activiti/activiti-cloud-audit/blob/develop/src/main/resources/logback-spring.xml . The tricky thing would be to avoid ending up with lots of effectively duplicated configuration for different combinations like 'local and debug', 'local and not debug', 'kube and debug' etc. Would be better if we could reference a property in the logback file but not sure we can do that. But not sure we can avoid that problem without doing it programmatically (https://github.com/Activiti/activiti-cloud-audit/pull/17) which is probably more work than it is worth right now so might have to live with the duplication.

**Comment by ffazzini** [comment]
I agree that I would not use profiles for things like logging level, otherwise we will start using profiles in an inconsistent way(for everything basically). If you want to see our own logs we only need to write more log.info() statements which we don't have any at the moment. I would start with that honestly instead of making complex straight away as we may not ever need that level switch. Adding more logs it is absolutely necessary otherwise we won't be able to go deeper when we have to troubleshoot problems. If you think that parameterising logging level via env variable is still important you can use ```<property resource="application.properties" />``` in the logback file.

**Comment by ryandawsonuk** [comment]
The property option sounds good. It seems inevitable to me that some day our users will want to be able to enable debug logging.

**Comment by ryandawsonuk** [comment]
Though I do agree it's not an immediate need.

**Comment by ffazzini** [comment]
If logs are written properly you won't need to disable them, the user will benefit of these logs either on local or prod environment. For debugging purpose I would probably use other tools and not logging.

In the rare case the user would not need these logs, yes the env variable is the best option. But the user could still be able to disable manually once for all in the logback file.

**Comment by lucianoprea** [comment]
I'll put this back in backlog until we agree what is the best solution.

**Comment by ryandawsonuk** [comment]
I think support through environment variables is enough given that our charts now [support injection of environment variables through `extraEnv`](https://github.com/Activiti/activiti-cloud-charts/blob/bb37c0779b93c6ceff6129e899795659af845a95/activiti-cloud-full-example/values.yaml#L16). Spring boot's relaxed binding means we can set `DEBUG` or `SPRING_PROFILES_ACTIVE` or both so this is pretty flexible.
