### ISSUE TITLE
Spring Cloud Stream channel resiliency and message delivery guarantees

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#1801]
Points from the catch-up on March 1, 2018 for review:

1) Look at the acknowledgement strategy used when consuming messages with streams - might be why message seems to be consumed even in a failure case (Activiti/Activiti#1799 )

2) Look at whether transmission of the message on the producer side is linked to the spring transaction or whether we need to enable a RabbitMQ feature for that

3) Are the queues that we're creating durable? Will messages on them be retained even if RabbitMQ goes down? Need to check what spring cloud streams default is.

4) How resilient Spring Cloud Stream producer and consumer channel bindings to handle message broker restarts? Do they automatically reconnect after losing connection with message broker? What is the re-connection strategy, i.e. fixed interval, exponential backoff? How many re-connection attempts do they make?

**Comment by ryandawsonuk** [comment]
There are also the official spring tests https://github.com/spring-projects/spring-framework/blob/master/spring-tx/src/test/java/org/springframework/transaction/event/TransactionalEventListenerTests.java

Another interesting article is http://lifeinide.com/post/2017-12-29-spring-boot-rabbitmq-transactions/

And also see https://stackoverflow.com/questions/42372747/rabbitmq-and-delivery-guarantees-in-distributed-database-transaction - that seems to me to come closest to what we might consider

What we could consider doing is persisting an event to the RB database as part of the transaction, performing the send in the after_commit and clearing out the event after the send completes so that we can establish when a delivery failure has occurred. That introduces a risk of sending the event twice but that's ok so long as the consumers are able to handle that eventuality and ignore the second instance. 

If we knew who the expected consumers were then we could also have them send an acknowledgement (perhaps as an optional configuration) and on receipt of the acknowledgement we could clear out the RB's record of the event (if it hasn't already been removed) to ensure we don't send again. (In the case of connectors we actually do get acknowledgements anyway.)

**Comment by igdianov** [comment]
Re: 2) Look at whether transmission of the message on the producer side is linked to the spring transaction or whether we need to enable a RabbitMQ feature for that

Spring Cloud Stream Rabbit binder implements transaction synchronization support with `PlatformTransactionManager` for producers: https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/blob/master/spring-cloud-stream-binder-rabbit/src/main/java/org/springframework/cloud/stream/binder/rabbit/RabbitMessageChannelBinder.java#L584

The producer output stream in rabbit binder configuration needs to be declared as transacted: `spring.cloud.stream.rabbit.bindings.output.producer.transacted=true`

After that, the `MessageProducerCommandContextCloseListener.closing(CommandContext commandContext)` method should be annotated with `@Transactional` to join Activiti transaction when sending events:

```
 @Override
 @Transactional
    public void closing(CommandContext commandContext) {
        List<ProcessEngineEvent> events = commandContext.getGenericAttribute(PROCESS_ENGINE_EVENTS);
        if (events != null && !events.isEmpty()) {
            boolean sent = producer.auditProducer().send(MessageBuilder.withPayload(
                    events.toArray(new ProcessEngineEvent[events.size()]))
                                                  .build());
            if(!sent) {
                throw new ActivitiException("Cannot send audit events to producer channel.");
            }
        }
    }
```
Now, in theory,  if Activiti successfully commits its transaction, the producer channel will also execute commit to publish messages. 

In the event Activiti database transaction is rolled back, the producer channel will rollback messages waiting for commit the output stream channel as well.

If there is infrastructure problem and message cannot be sent, producer send() method will return false and raise `ActivitiException` to Activiti closing manager to rollback database transaction.

**Comment by Salaboy** [comment]
@igdianov this is great.. I think that the only piece missing is to add some kind of flag to be able to configure the behaviour of those rollbacks.. 
I'm not 100% sure that you want to rollback if you cannot send the audit message, for some scenarios that is a must, for some others might not be. I'm wondering what is the best approach, and where is the line of what can cause a rollback and what can't. 

I've seen places, where even if the audits are a must, a mechanism needs to be implemented to retry sending the audit events, some kind of local cache, but that also introduce having a mechanism that is locally and can be handled inside a transaction.

**Comment by igdianov** [comment]
@salaboy @ryandawsonuk @erdemedeiros Very good detailed explanation about RabbitMQ message delivery resiliency: https://github.com/rabbitmq/workloads/blob/master/resiliency/README.md
