### ISSUE TITLE
  We suspect that it was an error when the process parsed the XML file

### ISSUE THREAD

**Issue by wxp20032003** [Activiti/Activiti#1930]
Our process runs normally within four or five days after the service is started, but there will be an end of the interruption after four or five days on the line, and no reason can be found.We suspect that it was an error when the process parsed the XML file
![mytaskaction_hsipreview](https://user-images.githubusercontent.com/13210205/42493157-594ed688-844e-11e8-822e-91d90bb26ecd.png)
[gongxun5.txt](https://github.com/Activiti/Activiti/files/2179122/gongxun5.txt)

**Comment by wxp20032003** [comment]
<exclusiveGateway id="exclusivegateway4" name="Exclusive Gateway"></exclusiveGateway>
    <sequenceFlow id="flow24" name="维修处理" sourceRef="exclusivegateway4" targetRef="task5">
      <documentation>{"selectPeople":"YES","goLevel":"","goDepType":"WHDW","nextPar":"mTeam","role":"维护单位负责人"}</documentation>
      <conditionExpression xsi:type="tFormalExpression"><![CDATA[${outcome=='维修处理'}]]></conditionExpression>
    </sequenceFlow>
    <sequenceFlow id="flow25" sourceRef="task3" targetRef="exclusivegateway4"></sequenceFlow>
    <sequenceFlow id="flow26" name="问题筛分上报" sourceRef="exclusivegateway4" targetRef="task4">
      <documentation>{"selectPeople":"YES","goLevel":"UP","goDepType":"ZXJ","nextPar":"voiceDirect","role":"工程巡查管理人员"}</documentation>
      <conditionExpression xsi:type="tFormalExpression"><![CDATA[${outcome=='问题筛分上报'}]]></conditionExpression>
    </sequenceFlow>

**Comment by wxp20032003** [comment]
and no error log can be fount

**Comment by Salaboy** [comment]
@wxp20032003 so what is the problem exactly? I can see that the process is stuck in the User Task (last task in red)

**Comment by wxp20032003** [comment]
@Salaboy ,this image is no error with arrowhead, but image in the top stuck in the User Task that process is complete.
    This process in the process sometimes can pan pass,but sometimes stop and processInstance is complete,not regular.
![mytaskaction_hsipreview 1](https://user-images.githubusercontent.com/13210205/42854996-191aecf4-8a71-11e8-868f-e6065cd55146.png)
![mytaskaction_hsipreview](https://user-images.githubusercontent.com/13210205/42854998-1a6c8464-8a71-11e8-8f9b-2e44a9d4ed7a.png)

**Comment by Salaboy** [comment]
@wxp20032003 I really want to help, but that might be happening for a thousand reasons. is it possible for you to create a small project with a reproducer? that usually help us to understand the problem or even to find the actual cause of it.

**Comment by wxp20032003** [comment]
@Salaboy  Thank you all the same, the project is so complicated that I can not create a small project with a small project with a reproducer! Let me  add that  after I restart my web application, in the first three days, this process running normally,but after that this process sometimes can pass and sometimes can not pass(the processInstance is null). 
Now i change the bpmn as shown following,test  to see how effective!
![changed bmnp](https://user-images.githubusercontent.com/13210205/42869727-7326f648-8aa8-11e8-96a2-c131f51a3070.jpg)

**Comment by Salaboy** [comment]
@wxp20032003 I do understand that the project is complicated, but I would suggest to try to replicate the scenario in a simple test. For example, if you know that the problem is in a user task, try to replicate the execution of your user task (adding similar listeners, and environment configurations) to your test. 
Working on a reproducer will help you to understand all the details of the execution and probably highlight the problem. If it is something that is failing every 3 days, it must be related with 
1) race condition
2) are you using async executions?
3) are you setting up listeners on events that are executed on the same DB transaction?

**Comment by wxp20032003** [comment]
My web application framework is struts2+spring+hibernate, There is a web application in eight docker,  the eight web application connect one mysql DB.
If I meet with what you say three questions, what should I do?
![datadd](https://user-images.githubusercontent.com/13210205/42871665-7d98e56e-8aad-11e8-9a30-9b0698e01c73.jpg)

**Comment by wxp20032003** [comment]
The stuck means that this processInstance is null in table act_ru_execution.
Outgoing conditions of  the second exclusicve gateway variables is chinese, the variables of outgoing conditions has been assigned exist in table act_hi_varinst, I don't know why the process complete.
`	@Override
	public void approve(ApproveInfo approveInfo, String taskId, Map<String, Object> map) throws Exception {
		// 1，保存本次审批信息
		getSession().save(approveInfo);
		Application application = approveInfo.getApplication();
		// 办理完任务
		Task task = processEngine.getTaskService().createTaskQuery().taskId(taskId).singleResult();// 使用任务ID查询
		Method method = Application.class.getMethod("get" + application.getBussinessType());// 得到表单对象的get方法，得到表单对象。
		Object object = method.invoke(application); // 得到表单对象。
		Method nameMethod = object.getClass().getMethod("setStatus", new Class[] { String.class });// 得到setStatus方法。
		processEngine.getTaskService().claim(task.getId(), map.get("user").toString());// 先claim，认领任务。
		processEngine.getTaskService().complete(task.getId(), map);// 完成任务。
		ProcessInstance pi = processEngine.getRuntimeService().createProcessInstanceQuery().processInstanceId(task.getProcessInstanceId()).singleResult();
		if (pi == null)// 说明流程结束了。
		{

			nameMethod.invoke(object, new Object[] { Application.STATUS_OVER });// 给set方法赋值。
			application.setStatus(Application.STATUS_OVER);
			getSession().update(object);
			getSession().update(application);
		}
		/*
		 * 如果outcome是驳回，证明不同意，就是驳回(制定计划用)。
		 */
		if ("驳回".equals(map.get("outcome")) && application.getPlans() != null) {
			nameMethod.invoke(object, new Object[] { Application.STATUS_REJECTED });// 给set方法赋值。
			application.setStatus(Application.STATUS_REJECTED);
			getSession().update(object);
			getSession().update(application);
		}
	}`

**Comment by wxp20032003** [comment]
@ryandawsonuk @Salaboy activiti 5.22 doesn't support  distributed servers?

**Comment by daisuke-yoshimoto** [comment]
@wxp20032003 No. Activiti 5.22 supports cluster environment. What do you mean it?

**Comment by ryandawsonuk** [comment]
I'm confused by

> Outgoing conditions of the second exclusicve gateway variables is chinese, the variables of outgoing conditions has been assigned exist in table act_hi_varinst, I don't know why the process complete.

I thought the problem was that it gets stuck at the user task? Why do you say "I don't know why the process complete"? Does it get stuck or does it complete?

The key question about the second exclusive gateway's outgoing sequence flow conditions is whether the value of the variable matches either of the conditions for the instances in which it gets stuck. Have you been able to find a case where the 'outcome' variable matches either '合同外' or '合同内' (these values seem to be the conditions on the outgoing sequence flows for the second gateway, which is confusingly called 'exclusivegateway3') but expected sequence flow was not taken?

Maybe instead of using the form `${outcome=='合同外'}` you could instead use a conditionExpression that is implemented in code and which evaluates to either true or false. Then your code could also log the value and whether it matches. (Rather like https://github.com/Activiti/ttc-rb-english-campaign/blob/develop/src/main/resources/processes/en-campaign.bpmn20.xml#L15 and https://github.com/Activiti/ttc-rb-english-campaign/blob/develop/src/main/java/org/activiti/cloud/runtime/controllers/CampaignController.java#L39)

**Comment by wxp20032003** [comment]
@Salaboy @ryandawsonuk After I redraw the BPMN,the problem that the process stuck has  disappeared，thank you very much！

**Comment by Salaboy** [comment]
yey! @wxp20032003 congrats!

**Comment by wxp20032003** [comment]
Problems still exist. 
@Salaboy @ryandawsonuk 
![mytaskaction_hsipreview](https://user-images.githubusercontent.com/13210205/44029572-5bbcf498-9f30-11e8-814f-f72888d1ecd3.png)
![qq 20180813193151](https://user-images.githubusercontent.com/13210205/44029578-6067577c-9f30-11e8-9b91-356593ff23b5.png)
![qq 20180813193459](https://user-images.githubusercontent.com/13210205/44029583-636179da-9f30-11e8-8260-8b38be3addca.png)
I don't know what to do !

**Comment by salaboy** [comment]
@wxp20032003 unless we can reproduce the problem, it is impossible for us to fix it. My recommendation is to create a reproducer and try to find what is different in your environments.

**Comment by mteodori** [comment]
obsolete
