### ISSUE TITLE
getting started / Quickstart broken

### ISSUE THREAD

**Issue by ChuckIrvine** [Activiti/Activiti#1934]
I'm not sure if I'm reporting this in the right place. I'm new to Activiti 7.x.

* I followed the instructions at: https://activiti.gitbooks.io/activiti-7-developers-guide/getting-started/quickstart.html. 
* After executing the second docker-compose command, per the documentation I tried to login at http://localhost:3000. Nothing seems to be running on that port. 
* On a hunch, I tried http://localhost:8080 and did get the login page. Tried to log with test user/password. That gave me: 
```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jul 11 19:24:10 GMT 2018
There was an unexpected error (type=Not Found, status=404).
Not Found
```
At this point, I'm wondering if I'm using some stale docs of some sort. 

Any ideas?

**Comment by Salaboy** [comment]
@ChuckIrvine you are definitely reporting this in the right place. We appreciate your input. 
Activiti 7/Activiti Cloud is in alpha state right now. We are trying to wrap a Beta1 release soon, so our docs are getting out of date. 
I would strongly recommend you to use the PostMan Collection that you can find in the activiti-cloud-examples repository instead of trying the UI that doesn't have much functionality right now. 
I will update the quickstart right now to reflect that. 
I also recommend you to join the gitter channel, so if you have questions we can try to tackle them as quick as possible.

**Comment by Salaboy** [comment]
We also recommend for now to try the develop branch of activiti-cloud-examples

**Comment by Salaboy** [comment]
I've updated the quickstart now: https://activiti.gitbooks.io/activiti-7-developers-guide/content/getting-started/quickstart.html
