### ISSUE TITLE
Task name required to create a task in Java and REST apis

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#1953]
While creating standalone task, the task name should be required and validated.

**Comment by salaboy** [comment]
merged

**Comment by ryandawsonuk** [comment]
We are seeing
```
[ERROR] Tests run: 229, Failures: 1, Errors: 1, Skipped: 7, Time elapsed: 121.301 s <<< FAILURE! - in org.activiti.cloud.qa.AcceptanceTests
[ERROR] Then notifications are received(org.activiti.cloud.qa.story.ProcessInstanceNotifications)  Time elapsed: 20.039 s  <<< FAILURE!
java.lang.AssertionError: VerifySubscriber timed out on reactor.core.publisher.ReplayProcessor$ReplayInner@7cf2f5af
    at org.activiti.cloud.qa.story.ProcessInstanceNotifications.verifyNotifications(ProcessInstanceNotifications.java:87)

[ERROR] And we set task variable start1 to start1modified(org.activiti.cloud.qa.story.Tasks)  Time elapsed: 0.311 s  <<< ERROR!
feign.FeignException: 
status 500 reading TaskRuntimeService#setTaskVariables(String,SetTaskVariablesPayload); content:
{"timestamp":"2019-02-06T16:51:55.132+0000","status":500,"error":"Internal Server Error","message":"BEST_MATCHING_HANDLER_ATTRIBUTE","path":"/v1/tasks/80e28908-2a2f-11e9-82a8-0a580a34043b/variables"}
    at org.activiti.cloud.qa.story.Tasks.setTaskVariableValue(Tasks.java:178)
```
In http://jenkins.jx.35.228.195.195.nip.io/job/Activiti/job/activiti-cloud-example-chart/job/PR-74/

breaking change is in 108 of application chart, which upgraded to 7.0.17 of notifications-graphql, which came from that repo accepting 7.0.172 of cloud-deps, which happened because rb-service went to 7.0.118 (actually 7 hours ago, so before the upgrade) which was because of a change at core level to take activiti-dependencies to 7.0.99, which was from engine version 7.0.121, which is that task name change - https://github.com/Activiti/Activiti/commits/v7.0.121

**Comment by salaboy** [comment]
@igdianov can you please check this one?

**Comment by igdianov** [comment]
@salaboy So, I am able to reproduce this problem by running Example Microservice Spring Boot App locally. There are two workarounds available that fix the error:

a. Downgrade to SB 2.0.0.RELEASE
b. Disable MetricsAutoConfiguration with @SpringBootApplication(exclude = MetricsAutoConfiguration.class)

I have raised an issue with SB: spring-projects/spring-boot#15860

**Comment by CTI777** [comment]
@ryandawsonuk @salaboy 
Do we have any additional issues regarding PR's from here or not?

**Comment by salaboy** [comment]
closing this again because this was not the cause of the issue.
