### ISSUE TITLE
[Core] Make sure message producers declare required groups from starter

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2258]
Currently the property [is set in the example only](https://github.com/Activiti/example-runtime-bundle/blob/master/src/main/resources/application.properties#L6..L7), but it will be great to have it automatically loaded by an auto configuration at the starter level.

**Comment by ryandawsonuk** [comment]
Ideally we'd like to include the destination in the autoconfiguration too. But then the events channel would be hard to disable. As discussed on gitter, what we really want is a set of flags to disable features in the RB starter:

activiti.cloud.connector.messaging.enabled
activiti.cloud.events.messaging.enabled
activiti.cloud.rest.enabled
activiti.cloud.keycloak.enabled

Doing that would encompass https://github.com/Activiti/Activiti/issues/1377 and lead to refactoring outlier property names like https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/conf/activiti/services/connectors/CloudConnectorsAutoConfiguration.java#L50

Then most or all of the [properties in the example RB](https://github.com/Activiti/example-runtime-bundle/blob/master/src/main/resources/application.properties) would move to starter level

Non-cloud property names [would remain `spring.activiti`](https://github.com/Activiti/Activiti/blob/develop/activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ActivitiProperties.java#L23)

**Comment by ryandawsonuk** [comment]
The renaming of properties would mean updating other example projects such as TTC, and [quickstarts](https://github.com/Activiti/activiti-cloud-runtime-bundle-quickstart)

**Comment by ryandawsonuk** [comment]
Looking like some refactoring is going to be needed in order to support the kind of conditional loading we're proposing. I've locally tried removing the `@ComponentScan("org.activiti")` from https://github.com/Activiti/Activiti/blob/develop/activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/EndpointAutoConfiguration.java#L29 and unfortunately things do break... that was not there in v6 https://github.com/Activiti/Activiti/blob/6.x/modules/activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter-basic/src/main/java/org/activiti/spring/boot/EndpointAutoConfiguration.java#L30 There are other compontscans in our codebase but this one is especially broad and restricts our ability to do conditional loading in RB

**Comment by ryandawsonuk** [comment]
Have created branch `ryan-2258autoconfig` in activiti-core-common, Activiti, activiti-cloud-runtime-bundle-service and example-runtime-bundle but **don't have it working yet**.

**Comment by ryandawsonuk** [comment]
Have updated the branches but still hitting problems.  Am finding I need to load ProcessEngineAutoConfiguration before CloudConnectorsAutoConfiguration in order to get a bean of IntegrationContextServiceImpl available but then CloudConnectorsAutoConfigurationIT hits a nullpointer at https://github.com/Activiti/Activiti/commit/f0e8af39fa154fa8fa2b659dc9a902db25fd466c#diff-e4065a18b1a2c02a65013c84926b9695R48 because the repositoryService is mocked and I'm struggling to find a way to get access to the mock in https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/450f89b915ba56c56358bd03cb15bba716d4a5ba/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/test/java/org/activiti/services/connectors/conf/CloudConnectorsAutoConfigurationIT.java#L50

I'm also finding that activiti-examples don't work with these changes as UserGroupManager doesn't get loaded
