### ISSUE TITLE
Add admin delete process endpoint

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2369]
Add endpoint DELETE `admin/v1/process-instances/${processInstanceId}`. Similar to https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-api/src/main/java/org/activiti/cloud/services/rest/api/ProcessInstanceController.java#L46

**Comment by CTI777** [comment]
@erdemedeiros @salaboy 
**Question 1**
Is it good that we do not check status of the process before it is deleted?
Maybe it will have a sense to allow admin to delete process always, other users may delete process only in some states (not running)? 
**Question 2**
In the endpoint for process delete we do not have a possibility to set a reason (it can be useful for the end user) and it can be set inside DeleteProcessPayload:
https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-api/src/main/java/org/activiti/cloud/services/rest/api/ProcessInstanceController.java#L46

Maybe it will have a sense to add something like this:
@RequestMapping(value = "/{processInstanceId}", method = equestMethod.DELETE)
ProcessInstanceResource deleteProcessInstance(@PathVariable("processInstanceId") String processInstanceId,
@RequestBody DeleteProcessPayload payload)

**Comment by salaboy** [comment]
@CTI777 great comments! 
For question 1: I would say that not for now.. we need to think about which kind of limitations we will add for normal users
For question 2: you are right.. we need to see if the internal API support a reason for deletion, because if we add it to the payload but we don't store it somewhere (maybe it is enough to store it in query service) .
