### ISSUE TITLE
Make BPM model available in query service 

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2389]
Related to endpoint `GET admin/v1/process-instances/${id}/model`.
Some decisions should be taken for this issue. Currently this endpoint on runtime bundle is capable of returning a SVG image highlighting the active flow nodes for the given process instance. However this requires the list of active flow elements in the process instance, information that we don't have out of the box on query. It need to be calculated from the list of task in different states.

**Comment by mauriziovitale** [comment]
I had a quick chat with @popovicsandras , right now we don't have a component that can be reused to view the process definition. He told me that bpm.io has API for Edit and View a process definition XML. So it should not be difficult to create a component that shows the process definition starting from the .xml but will be painful add the other stuff like "decorations" because there is no documentation.

@magemello @mteodori is it fine for you if as first step we try to display the process definition and later on we will try to add all the decorators?

**Comment by erdemedeiros** [comment]
Only `
GET admin/v1/process-definitions/${id}/model` returning the `XML` file is being covered by this implementation.

**Comment by ryandawsonuk** [comment]
https://github.com/Activiti/activiti-cloud-acceptance-scenarios/pull/215 was merged into master but we had already created the 7.0.0.SR1 release at that point so it was too late for cherry-picking into that. That test currently not in the 7.0.x branch
