### ISSUE TITLE
Start Process - inconsistency of parameter name in request/response for process name

### ISSUE THREAD

**Issue by rgherghelas** [Activiti/Activiti#2393]
Steps to reproduce the issue:
Start a process and check the request and response.

Current behaviour:
Different parameter names for the the process name*.* Please see attached pictures.

<img width="641" alt="screen shot 2019-01-21 at 11 14 27 am" src="https://user-images.githubusercontent.com/39947234/51481559-d2305f80-1d9c-11e9-9b5d-5aee54f5d3b6.png">

![screen shot 2019-01-21 at 11 18 04 am](https://user-images.githubusercontent.com/39947234/51481668-0dcb2980-1d9d-11e9-82d5-4f3b85fbeaf1.png)

**Comment by CTI777** [comment]
@salaboy @erdemedeiros 
StartProcessPayload and UpdateProcessPayload have:
processInstanceName
In response we have name because it is a property of ProcessInstance
What should I change: response or Payload?
I think that changes in StartProcessPayload and UpdateProcessPayload will be less expensive...

**Comment by erdemedeiros** [comment]
@CTI777 let's change the properties of Payloads to `name` to keep consistent with a similar change done for tasks https://github.com/Activiti/Activiti/issues/2355.

**Comment by salaboy** [comment]
merged and it will be included in RC1
