### ISSUE TITLE
Mismatch between Query and Runtime Bundle on Standalone Task Deleted

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2462]
When calling RB DELETE standalone task the Task Status is DELETED,
when looking at the status of the task in QUERY we get CANCELLED. 
Reported by @mauriziovitale

**Comment by mauriziovitale** [comment]
Create a task
<img width="422" alt="screenshot 2019-02-07 at 10 17 11" src="https://user-images.githubusercontent.com/14923305/52404762-aeba2400-2ac1-11e9-94dd-86540477b1d7.png">

Delete the task

<img width="572" alt="screenshot 2019-02-07 at 10 17 28" src="https://user-images.githubusercontent.com/14923305/52404761-ae218d80-2ac1-11e9-9986-d50e7407e3bb.png">

Query the task
<img width="598" alt="screenshot 2019-02-07 at 10 17 43" src="https://user-images.githubusercontent.com/14923305/52404760-ae218d80-2ac1-11e9-892e-3caf92d449fa.png">

**Comment by miguelruizdev** [comment]
There's no bug related to this, the mismatch is caused by not having a clear definition of **CANCELLED** or **DELETE** status (and subsequently, the act of canceling or deleting).

That can be seen here:
https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/c5b798486db954ad9abdbad27beda315ec4bdcb9/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/AuditProducerIT.java#L358

In that test covering the deletion of a task, we are expecting a **TASK_CANCELLED** event and a **CANCELLED** status. That's what we send to Query.

The reason why we get the **DELETED** status in RB is that we build the returned task here:
https://github.com/Activiti/Activiti/blob/19a32c38eea29750c44ec5cb703f22ea2e031919/activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeImpl.java#L240

The [deleteTask method](https://github.com/Activiti/Activiti/blob/19a32c38eea29750c44ec5cb703f22ea2e031919/activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeImpl.java#L244) as void as a return type, and to be consistent with the REST practice of returning the modified resource, we created the task with **DELETED** status deliberately.

**Comment by salaboy** [comment]
@erdemedeiros can you think of a solution for this?
@miguelruizdev can you do a search for when and how we use Task.TaskStatus.DELETED?
if that is the only place where we use it.. we might want to use CANCELLED even for when the user do a DELETION. I remember that we created that DELETED state to make sure that we can differentiate a DELETE from the user and an automatic CANCELATION triggered by the process. But I guess that is causing problems in Query, that doesn't know how to recognize between the two.

**Comment by miguelruizdev** [comment]
More code that reflects the ambiguity of this two states:
https://github.com/Activiti/Activiti/blob/5fdfdc3888f454359c5b809a0c90ad561a331270/activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/model/impl/APITaskConverter.java#L52

There is no Deletion Event present in runtime bundle for Tasks:
https://github.com/Activiti/activiti-cloud-acceptance-tests/blob/f1fb164027227a80c12e1e26c294b842224ab47b/activiti-cloud-acceptance-tests-core/src/main/java/org/activiti/cloud/acc/core/steps/audit/AuditSteps.java#L332

Same for Processes:
https://github.com/Activiti/activiti-cloud-acceptance-scenarios/blob/23243a44b01a4616fafa0db2cfa280a641a9e3c9/runtime-acceptance-tests/src/main/java/org/activiti/cloud/qa/story/ProcessInstanceTasks.java#L276

Right now, there is no equivalent to [TaskCancelledEvent](https://github.com/Activiti/activiti-api/blob/develop/activiti-api-task-runtime/src/main/java/org/activiti/api/task/runtime/events/TaskCancelledEvent.java) or [ProcessCancelledEvent](https://github.com/Activiti/activiti-api/blob/develop/activiti-api-process-runtime/src/main/java/org/activiti/api/process/runtime/events/ProcessCancelledEvent.java) when it comes to deletetion (hypothetically, a **TaskDeletedEvent** or a **ProcessDeletedEvent**)

We need to decide whether we fully implement the DELETED status for tasks and processes or we get rid of it 
- https://github.com/Activiti/activiti-api/blob/develop/activiti-api-task-model/src/main/java/org/activiti/api/task/model/Task.java#L29 
- https://github.com/Activiti/activiti-api/blob/develop/activiti-api-process-model/src/main/java/org/activiti/api/process/model/ProcessInstance.java#L29

**Comment by miguelruizdev** [comment]
Presence of the status **DELETED** in tests:
https://github.com/Activiti/Activiti/blob/714e5a89efa4e813e68d576c1bb1791c47936095/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeDeleteTaskTest.java#L66

https://github.com/Activiti/Activiti/blob/5e5601192d731bcca5d0b1c8113f15a28ddb391c/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeTaskAssigneeTest.java#L81

https://github.com/Activiti/Activiti/blob/80bd521b795e40252b8718d74a20a1ae66a76334/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeStandaloneTaskTest.java#L71

Reference to it when dealing with status **CANCELLED**:
https://github.com/Activiti/activiti-cloud-acceptance-scenarios/blob/9d85a150d60f9d52cc17c63c2b02458bedf1002c/runtime-acceptance-tests/src/main/java/org/activiti/cloud/qa/story/Tasks.java#L119

**Comment by salaboy** [comment]
I have two options in my head right now:
1) Return CANCELLED status when the user manually delete a task and change to cancel() instead of delete the method in the API

2) Use the "reason" property to, in query also set the task status to DELETED when the user executed the delete operation. This will require that process engine cancellation of tasks modify the reason to make sure that we can distinguish them. 

@erdemedeiros opinions?

**Comment by erdemedeiros** [comment]
@salaboy @miguelruizdev, I think we can go with the first option, but maybe instead of renaming `delete` to `cancel`, just add `cancel` and mark `delete` as deprecated (to avoid breaking change in the API). Then `delete` implementation (deprecated method) will delegate its execution to `cancel` (new method).
**Note:** I think the REST API should be kept unchanged, I mean we should keep using `DELETE` verb and `/v1/tasks/{taskId}` as path. @salaboy @miguelruizdev does it make sense?

**Comment by salaboy** [comment]
@erdemedeiros my only fear with option 1 is that we cannot differentiate anymore if the task was deleted by the "delete()" method or automatically by the process engine on process cancellation. 

So even if we go for the first option as you suggested (which is the smaller change) we should make sure that we add a sensitive reason to be able to differentiate between the two cases.

**Comment by salaboy** [comment]
@erdemedeiros I would add the flag release notes required for this one.. not sure if it makes sense to keep a deprecated method at this point, as soon as we correctly document it.

**Comment by erdemedeiros** [comment]
Final solution was:
1. keep method signature (`delete`)
1. change status to Cancel
1. add delete reason
