### ISSUE TITLE
Timeout issue in pipelienes

### ISSUE THREAD

**Issue by almerico** [Activiti/Activiti#2471]
<img width="1238" alt="screen shot 2019-02-08 at 1 18 11 pm" src="https://user-images.githubusercontent.com/2116248/52480754-4b112300-2bb5-11e9-8980-a707e7b2d3ef.png">
<img width="994" alt="screen shot 2019-02-08 at 2 13 22 pm" src="https://user-images.githubusercontent.com/2116248/52480755-4b112300-2bb5-11e9-8e1d-5181ced1bc38.png">

**Comment by ryandawsonuk** [comment]
Just had an incidence of this `socket closed` on the `helm install`.

There were two example-chart pipelines running and everything else was queued. kubectl describe nodes showed cpu request usage on nodes of `91% 92% 98% 95% 89% 88%` and cluster reflected high resource usage

![image](https://user-images.githubusercontent.com/22754674/52651019-50d37500-2ee3-11e9-96f0-6f5160ce9c92.png)

I did kubectl get pods and helm list and didn't see any old helm releases - only the in-flight ones. But one of the two got stuck because it couldn't schedule all of the pods - this one http://jenkins.jx.35.228.195.195.nip.io/job/Activiti/job/activiti-cloud-example-chart/view/change-requests/job/PR-91/4/console I could see that one of its Pods wasn't getting scheduled as it showed as `Pending` from `kubectl get pods`. That must be why the pipeline got Socket closed on the helm install for that run. It then got stuck for ages before eventually giving up and deleting the namespace, freeing up the resources.

**Comment by almerico** [comment]
after add two more nodes to cluster and resource allocation changes I don't see it lately
