### ISSUE TITLE
audit and query postgress unavailable issue 

### ISSUE THREAD

**Issue by almerico** [Activiti/Activiti#2480]
@ryandawsonuk @salaboy I noticed that high failure threshold in query and audit causes long delay in Query service recovery if it can't connect to Postgresql on startup because it does not retry to reconnect to it after first failure.

**Comment by igdianov** [comment]
This behavior is not desirable. It is more likely to stall the deployment longer than needed

**Comment by igdianov** [comment]
@ryandawsonuk @almerico @igdianov about postgresql retryies -> https://stackoverflow.com/questions/39563585/how-do-i-get-spring-boot-to-automatically-reconnect-to-postgresql
we need to investigate that option. but also @almerico we can make sure that postgresql hhas enough resources to start fast
same as rabbit

**Comment by almerico** [comment]
@igdianov resources already added for internal charts  looks like works ok

**Comment by ryandawsonuk** [comment]
The requests in the internal charts are set a bit high right now - 800m CPU for runtime-bundle. That was too high for me to install on a cluster with 8vcpu and @miguelruizdev wasn't able to install on a cluster with 10vcpu - we both had to add extra resources to use that.

In the current activiti-cloud-charts the cpu request for runtime bundle is set at 200m and for me that started with zero restarts, though not exactly sure how long it took but it must have been within the retry threshold (which is what this issue is about):

![image](https://user-images.githubusercontent.com/22754674/52643835-b3257900-2ed5-11e9-9fb1-c94167915f70.png)

**Comment by almerico** [comment]
@ryandawsonuk @salaboy  I played with CPU values today. If rabbit and postgress set to 0.3 cpu services set to 0.2 and runtime bundle to 0.4 startup is finished in two mins.

**Comment by almerico** [comment]
liveliness probes updated so it wait much longer till restart

**Comment by ryandawsonuk** [comment]
We hit an issue with the pipelines themselves being unable to run today - https://github.com/Activiti/Activiti/issues/2471#issuecomment-462830260

As well as the resource usage of activiti pods, the maven build pods are also set to use a lot:

![image](https://user-images.githubusercontent.com/22754674/52655747-d3acfd80-2eec-11e9-9b1a-2cc82a9133e0.png)

I've been having a look with `kubectl top pods --all-namespaces` and I think 0.3 for rabbit might be too low and that might be a factor in startup time:

![image](https://user-images.githubusercontent.com/22754674/52655806-fdfebb00-2eec-11e9-9933-6a969ddf8830.png)

But the other pods don't appear to need what we're requesting for them. The maven build pods also don't seem to need more than 700m

**Comment by almerico** [comment]
@ryandawsonuk @salaboy  with CPU set to postgress: 300, query: 200, audit: 250, rb:400, modeling 200/400, keycloak: 250,  rabbit: 600m also set Jenkins  maven builder cpu to 500  
<img width="737" alt="screen shot 2019-02-13 at 1 12 37 pm" src="https://user-images.githubusercontent.com/2116248/52707797-3526a800-2f91-11e9-8326-f0ea436c1f27.png">

**Comment by ryandawsonuk** [comment]
Have increased the cpu requests for j[ust rabbit and keycloak in the user-facing charts](https://github.com/Activiti/activiti-cloud-charts/commit/d3962e91455562d56ded91191adc658f3c9190c3) (trying to keep the others fairly low) and now those do start quite quickly:

![image](https://user-images.githubusercontent.com/22754674/52707106-db1ce700-2f7e-11e9-8cdc-c043ea455a53.png)

**Comment by almerico** [comment]
looks like CPU for rabbit keycloak and postgress is most important 
here

**Comment by ryandawsonuk** [comment]
Occasionally though I do see a problem with the runtime bundle connecting to postgres. Only the runtime bundle, not the other services - query and audit connect fine every time. When it does happen the error in the runtime bundle is:

```
ework.beans.factory.BeanCreationException: Error creating bean with name 'processEngine': FactoryBean threw exception on object creation; nested exception is org.activiti.engine.ActivitiException: resource 'org/activiti/db/create/activiti.null.create.engine.sql' is not available
``
I think the problem is related to the activiti engine's autodetection mechanism to discover which database type it is running against - this error indicates it hasn't found one as it says `null` where it should say `postgres`. Ideally we would stop that happening but also when it does happen it would be best if the runtime bundle pod could be automatically killed. When it happens to me the runtime bundle just carries on running and I find myself having to kill it manually.

I only see this problem in the user-facing charts and only since merging the change there to use a single postgres instance shared on all services (which isn't in the internal charts yet).

**Comment by ryandawsonuk** [comment]
Interestingly I then switched to the examples GKE cluster and deployed the user-facing chart in a namespace there. Startup was a bit slower for the same chart. Also resource usage during startup goes quite high there:

![image](https://user-images.githubusercontent.com/22754674/52709393-9431f000-2f84-11e9-89e5-515fa16915cf.png)

And then after startup drops right down again:

![image](https://user-images.githubusercontent.com/22754674/52709429-a4e26600-2f84-11e9-90ba-3a9448313170.png)

I guess we are seeing differences because vcpu and mb ram are only an approximate way of standardising resources. The actual hardware providing the resources is different in these two clusters and so we see some variation in usage.

**Comment by ryandawsonuk** [comment]
I've had to [put the failureThreshold back down to what it was before](https://github.com/Activiti/activiti-cloud-charts/commit/cd6b7c0e9f8f29b2d60706afec47f038e32f1a7e#diff-2260d40254c25255d4f631152562f31aR80) in the new version of the user-facing charts so that RB at least gets restarted if it hits the postgres connection problem.

**Comment by ryandawsonuk** [comment]
I think the key remaining issue is the occasional `resource 'org/activiti/db/create/activiti.null.create.engine.sql' is not available` in runtime bundle. I suspect we could address that by changing [the detection mechanism](https://github.com/Activiti/Activiti/blob/531ad3c5d1f94cd5310a2b840fc7332f7d05d065/activiti-engine/src/main/java/org/activiti/engine/impl/cfg/ProcessEngineConfigurationImpl.java#L1126) to fall back on `spring.jpa.database.platform` or `spring.datasource.driverClassName` when the connection metadata isn't enough

**Comment by ryandawsonuk** [comment]
Have improved with an [initContainer approach](https://github.com/Activiti/activiti-cloud-charts/commit/8711cc0c7c4c87123cc14ba5b38ade9f7dda2e0a). Longer term we should look at the DB type detection mechanism.
