### ISSUE TITLE
[Cherry pick] #2389 to 7.0.x

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2574]

**Comment by erdemedeiros** [comment]
Related to make bpm models available in query-service (https://github.com/Activiti/Activiti/issues/2389). Related PRs on develop branch: 
- https://github.com/Activiti/activiti-api/pull/89
- https://github.com/Activiti/Activiti/pull/2549
- https://github.com/Activiti/activiti-cloud-api/pull/71
- https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/251
- https://github.com/Activiti/activiti-cloud-query-service/pull/194

**Comment by ryandawsonuk** [comment]
Have cherry-picked:

c8dc074a2d0a42d872f7623620e40dbae04e35b3 for activiti-api

**Comment by ryandawsonuk** [comment]
I am not so sure about what to do on https://github.com/Activiti/activiti-cloud-query-service/commit/c63cc64dbc649cf9b37e25d4c5946d8dcc41da45 for query-service
as that one gets a conflict on VariableCreatedEventHandler.java

I think because the history in develop:
https://github.com/Activiti/activiti-cloud-query-service/commits/develop/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/VariableCreatedEventHandler.java
contains:
https://github.com/Activiti/activiti-cloud-query-service/commit/cf9fa22bd884655ed006728a015c8ff771840819#diff-e37335fb585919ed8c24e93ce9194355
And that is not in the 7.0.x history:
https://github.com/Activiti/activiti-cloud-query-service/commits/7.0.x/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/VariableCreatedEventHandler.java

**Comment by ryandawsonuk** [comment]
For the 7.0.x branch I've cherry-picked both of those commits as it seems we want both fixes

**Comment by salaboy** [comment]
we need to cherry pick this one as well https://github.com/Activiti/activiti-cloud-acceptance-tests/pull/137

**Comment by erdemedeiros** [comment]
PRs for acceptance tests:
- https://github.com/Activiti/activiti-cloud-acceptance-tests/pull/137
- https://github.com/Activiti/activiti-cloud-acceptance-scenarios/pull/215

**Comment by salaboy** [comment]
Acceptance Test PR merged in 7.0.x
