### ISSUE TITLE
modeling UI doesn't use connector Ids anymore

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2589]
Recently this change was made:

https://github.com/Activiti/activiti-modeling-app/commit/f83c2e6184813fc104ac671e60a87b4f320d9bf2

But we have examples using those ids:

https://github.com/Activiti/activiti-examples/search?q=MoviesId&unscoped_q=MoviesId
https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-starter-runtime-bundle/src/test/resources/connectors/connector-with-variable-mapping.json

These json files aren't accepted as valid in the latest modeler. Apparently the UI guys removed this from the json because it was failing in the modeling backend.

Do we now change the examples or the modeler?

**Comment by erdemedeiros** [comment]
Related to https://github.com/Activiti/Activiti/issues/2529

**Comment by erdemedeiros** [comment]
Actions 
- remove id field from [ConnectorDefinition](https://github.com/Activiti/activiti-core-common/blob/develop/activiti-connector-model/src/main/java/org/activiti/core/common/model/connector/ConnectorDefinition.java#L7)
- modify [ConnectorActionDefinitionFinder](https://github.com/Activiti/Activiti/blob/develop/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/connector/ConnectorActionDefinitionFinder.java) to match `connectorName.actionName` instead of `connectorId.actionId`
- update process examples that were using `implementation=connectorId.actionId` to make them use `connectorName.actionName`

**Comment by CTI777** [comment]
@erdemedeiros 
It can be dangerous to change implementation to the format: ConnectorDefinitionName.ActionDefinitionName because, for example, event all our test connectors json files have same name... How can we be sure that user will not use same name inside connectors? 
```
<bpmn:serviceTask id="Task_1ylvdew" name="Process Image" implementation="Name of the connector.processImageActionName">
```

![image](https://user-images.githubusercontent.com/21080352/55350051-7597a200-54bb-11e9-9809-c60ab0108668.png)

**Comment by erdemedeiros** [comment]
@CTI777 the current test examples have the same name because they were not used before. You need to update them to make them similar to what we had for id, for instance `Process Image Connector`. And yes, the bean names should be updated as consequence.

Could you please add validation while loading the connectors. This is done [here](https://github.com/Activiti/activiti-core-common/blob/develop/activiti-spring-connector/src/main/java/org/activiti/core/common/spring/connector/ConnectorDefinitionService.java#L60). You should check that names are unique and have no `.` character.

**Comment by CTI777** [comment]
@erdemedeiros 
All needed changes for implementation part should be done. Tests are updated. 
Following is left for consideration:

-  should we remove id field from ConnectorDefinition
-  should we modify RB to remove ConnectorDefinition id field: 
https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/f094a9119fa7a5a375c2419a8579bad595fb520d/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/ConnectorDefinitionControllerImpl.java#L58
-  should we modify RB to remove ConnectorDefinition id field: 
https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/f094a9119fa7a5a375c2419a8579bad595fb520d/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/assemblers/ConnectorDefinitionResourceAssembler.java#L20
- should we made changes now for activiti-example
https://github.com/Activiti/activiti-examples/search?q=MoviesId&unscoped_q=MoviesId

**Comment by CTI777** [comment]
> - should we made changes now for activiti-example
https://github.com/Activiti/activiti-examples/search?q=MoviesId&unscoped_q=MoviesId

This is fixed now here: https://github.com/Activiti/activiti-examples/pull/89

**Comment by erdemedeiros** [comment]
Done.
