### ISSUE TITLE
[BPMN / Core] Business Rule Task - Decision Runtime (using Drools impl)

### ISSUE THREAD

**Issue by mteodori** [Activiti/Activiti#2628]
Use the cloud connector architecture to create a service which can evaluate DMN decision tables using the [Drools](https://www.drools.org/]) engine.

The connector will contain all the decision table descriptors that are needed in the DMN 1.1 format as supported by the [DMN JavaScript editor](https://bpmn.io/toolkit/dmn-js/) from bpmn.io.
At startup it will convert the decision table descriptors to the Drools format.

The decision table step in the process will have a specific implementation and action.
Implementation that specifies that this is a decision table task and an action that will specify the table to execute.
In addition to input variables that will passed to the connector and out variables that are expected from the connector.

**Comment by salaboy** [comment]
@mteodori @balsarori I wouldn't go for that (connector) approach it makes everyones life complicated and the management of the resources distributed. I think that you guys haven't considered the implications of creating a connector with such responsibilities. 

As I am saying since I started Activiti Cloud this should be the first steps for every component that we create
1) RFC about functionality and APIs
2) Spring Boot Starter to wrap external dependencies, in this case Drools
3) Clear interfaces to understand how the new component will be called
4) Extend the behaviour of the runtime bundle "Business Rule Task" to call this service if it is in the classpath, if the Bean (DecisionRuntime, similar to ProcessRuntime) in charge of the Runtime is not in the classpath a Default Bean should be provided to log that there is no service to execute the specified behaviour. 
5) Add the Business Rule Task element in the modelling experience
6) Make sure that we have acceptance tests for that

Does this make sense?

**Comment by salaboy** [comment]
@igdianov feel free to jump in if you have more thoughts about this.. but this is pretty much what we discussed back in DevCon

**Comment by balsarori** [comment]
@salaboy this is about DMN decision tables not Business Rule Tasks. I think the connector approach makes sense for decision tables execution not sure if it's applicable for Business Rule Tasks as well (I guess should be applicable for business rules as well).

**Comment by salaboy** [comment]
@balsarori let's have a quick chat.. that comment doesn't make sense to me

**Comment by salaboy** [comment]
@balsarori @mteodori please use Drools 7.x with the new KIE APIs .. try to not use older versions.
Also make sure that we don't do different things for DMN and Rules.. they should be both handled by the same set of APIs and starter.

**Comment by salaboy** [comment]
I will rename this issue to BPMN Business Rule Task to cover all the aspects that needs to be done for supporting this BPMN Element

**Comment by salaboy** [comment]
@balsarori @mteodori please create a google doc with an RFC so we can spec it and define what is going to be the initial iteration of the DecisionRuntime interface.

**Comment by mteodori** [comment]
I would keep it as a separate ticket, at the moment for APS we need a connector as in the original description of the ticket, no decision runtime, and as agreed we will have the same drools version of the dependency but these should remain separate concerns, we are not implementing the business rule task here

**Comment by mteodori** [comment]
won't do

**Comment by rguillome** [comment]
> @salaboy this is about DMN decision tables not Business Rule Tasks. I think the connector approach makes sense for decision tables execution not sure if it's applicable for Business Rule Tasks as well (I guess should be applicable for business rules as well).

Hi @balsarori 
I'm not sure to understand the difference between Decision tables and Business rule tasks. For exemple, [Camunda](https://docs.camunda.io/docs/components/modeler/bpmn/business-rule-tasks/) doesn't make any difference. 
What could be the use case to have a separated implementation between calling a decision table based task and a business rule task ?

Regarsd,

**Comment by balsarori** [comment]
Hi @rguillome 

In Activiti, we differentiate between [DMN](https://www.omg.org/dmn/) and business rules like `Drools Rule Language`. The core engine supports Drools (but that requires adding a lot of dependencies to the class path). As for connectors there could be a single connector that supports both DMN and DRL execution but I would rather have two different connectors.

Regards
