### ISSUE TITLE
proc def version needed in task instance

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2644]
Similar to https://github.com/Activiti/Activiti/issues/2643 but for this case the aim would be to allow a UI to find which version of a form it should use for a task. The information needs to be in the task instance so that the UI doesn't have to go through a chain of lookups.

**Comment by salaboy** [comment]
the impact of versioning all these in the DB will cause us a huge pain.. we need to design a proper solution

**Comment by magemello** [comment]
The version it's already in the db

**Comment by CTI777** [comment]
@igdianov @erdemedeiros 
To clarify steps to be done:

- Changes should be made in cloud-query-service (and if needed added to other modules, like audit services…).

- A new filed will be added to TaskEntity:
 ```private Integer processDefinitionVersion;```

- This filed will be applied in ```TaskCreatedEventHandler``` (we set already here ```proocessInstance``` for not standalone tasks) 

- A test should be added / extended

- Please add if I have to consider something additionally

**Comment by erdemedeiros** [comment]
@CTI777 you can start by query, but we'll also need to at this information to runtime bundle as well so that the response from runtime bundle and query don't get out of sync. You'll need to add an extra field in the API as well.

**Comment by erdemedeiros** [comment]
@CTI777 in any case you need to have it in the API because [query controller](https://github.com/Activiti/activiti-cloud-query-service/blob/develop/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/TaskController.java#L130) is returning a `CloudTask`.

**Comment by CTI777** [comment]
@erdemedeiros If we need this info also in runtime bundle we have to do much more changes.
For example in activiti core we have TaskConverter:
```https://github.com/Activiti/Activiti/blob/5fdfdc3888f454359c5b809a0c90ad561a331270/activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/model/impl/APITaskConverter.java#L31```
It will not work proper for `processDefinitionVersion`, because this filed is not defined in internal activiti task:
`https://github.com/Activiti/Activiti/blob/9b0be98e517e21f3cc3e83b649d8f926917b52d9/activiti-engine/src/main/java/org/activiti/engine/task/TaskInfo.java`

**Comment by erdemedeiros** [comment]
@CTI777 I've just checked with @salaboy. Let's cover only query for now. Runtime bundle will have the field as it's part of the API, but it will be always null (at least for this iteration).

**Comment by CTI777** [comment]
@erdemedeiros @salaboy 
I have updated **query-service** and test to handle processDefinitionVersion from event, not task entity as before

**Comment by salaboy** [comment]
done in develop

**Comment by salaboy** [comment]
@CTI777 can you please this one if it is done?

**Comment by CTI777** [comment]
@salaboy   it is done. What should I do? It is closed...
