### ISSUE TITLE
The TaskVariableController was modified to set task variable per call

### ISSUE THREAD

**Issue by pancudaniel7** [Activiti/Activiti#2677]
The old implementation of creating task variables with one call was modified to create one task variable per call.

**Comment by magemello** [comment]
This seams to be a breaking change introduced in this task:
https://github.com/Activiti/Activiti/issues/2515

Can we reenable the ability to set multiple variables with a single call? This breaking change has broken the logic of one of the enterprise services.

**Comment by magemello** [comment]
Also I'm not sure about this strict logic between create and update. Let's suppose I have a task with 100 variables and I do the save of 50 of them......then a second time I save  all 100 am'I suppose to know which one are new and which one were already saved? Also am'I suppose to do 2 calls? One to update the previous 50 and another to create the new 50? Isn't to much complicate?

**Comment by magemello** [comment]
I would suggest to add also 
```
    @RequestMapping(value = "/", method = RequestMethod.PUT)
    ResponseEntity<Void> updateVariables(@PathVariable String taskId,
                                        @RequestBody UpdateTaskVariablesPayload updateTaskVariablePayload);
```

**Comment by salaboy** [comment]
I think that we need to evaluate what are the use cases that we want to cover. 
@balsarori @pancudaniel7 can you please clarify how the internal form service is using these endpoint and when? 

In my opinion we should have a save(SaveTaskPayload) Task operation similar to complete() which uses this payload: 
https://github.com/Activiti/activiti-api/blob/develop/activiti-api-task-model/src/main/java/org/activiti/api/task/model/payloads/CompleteTaskPayload.java 

@magemello I am happy to revert back the following method if that broke backward compatibility from SR1 to GA, but I wouldn't suggest the usage of that method. It will be a terrible decision to keep using that from components instead of having a clear/clean new set of APIs. Even if we revert it back we will mark it as @Deprecated

```
@RequestMapping(value = "/", method = RequestMethod.PUT)
    ResponseEntity<Void> updateVariables(@PathVariable String taskId,
                                        @RequestBody UpdateTaskVariablesPayload updateTaskVariablePayload);
```

@erdemedeiros opinions?

**Comment by CTI777** [comment]
Maybe we can simply add a method setTaskVariables
Then we will have a clean and straightforward create / update methods with checking of everything for one variable.
But additionally, there will be a method to setTaskVariables (multiple variables) which will create variable if needed or update it if it exists... Maybe it is possible to configure that this method will be available not always and not for everybody... Maybe only for admin?

**Comment by salaboy** [comment]
@CTI777 I really want to avoid having a "variable manipulation method" that is too low level and it doesn't map to an operation that the user is performing. Our new APIs needs to be extremely clear in the behaviour. 
This cannot be admin only because it is going to be executed by our forms mechanism which is a user operation

**Comment by CTI777** [comment]
@salaboy I am also completely against multiple variable manipulation method. And the proposal was for the case there is no way to avoid this...

**Comment by salaboy** [comment]
Going back to my proposal:
```
save(SaveTaskPayload)
```

Where SaveTaskPayload will have like complete a Map of variables.

**Comment by salaboy** [comment]
As mentioned by @igdianov we should add a flag to see which variables are local and which are not.

**Comment by salaboy** [comment]
@igdianov no admin for now.. we can add that later.

**Comment by salaboy** [comment]
Ok so more refinements:
- Let's use the save method to store local task variables
- Let's use complete() and the Payload to in the backend check the content of the variables map and do
  - If the variable exist in the process scope propagate it
  - If it doesn't exist in the task level create it
  - if it exist in the task level update

By following this logic there are no two maps in the CompleteTaskPayload which is very confusing and at the same time reduce the responsibility of the operation and hide the internal logic in the implementation without leaking it out to the clients.

**Comment by igdianov** [comment]
@Salaboy when user completes the task form,  he will need to inject form outcome variable, i. FormResult with values Approve or Reject into process scope. Based on the logic you propose,  the FormResult variable will not be propagated because it does not exist yet.

**Comment by igdianov** [comment]
I think complete task paylod should have single responsibility to complete the task with provided variables propagated into process.

**Comment by pancudaniel7** [comment]
Right now on my side on form-service, when I am trying to save a form first of the step is to set the task variables. This is the current implementation:
```
runtimeBundleFeignClient.setVariablesLocal(taskId, setTaskVariablesPayload); 
```

```
@RequestMapping(method = RequestMethod.POST, consumes = "application/json", produces = "application/json",
            path = "/v1/tasks/{taskId}/variables")
    void setVariablesLocal(@PathVariable(value = "taskId") String taskId,
                               @RequestBody(required = false) SetTaskVariablesPayload setTaskVariablesPayload);
```

**Comment by igdianov** [comment]
@pancudaniel7 See the following PR with proposed implementation: https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/296

**Comment by salaboy** [comment]
all merged now
