### ISSUE TITLE
Coolest code ever >_<

### ISSUE THREAD

**Issue by ggrnd0** [Activiti/Activiti#2687]
https://github.com/Activiti/Activiti/blob/35be47101f5450df20d9c7c3d74524c31788dbc6/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityImpl.java#L476-L482

**Comment by salaboy** [comment]
@ggrnd0 you can use BLAME in github to see who the author is :) 

https://github.com/Activiti/Activiti/blame/35be47101f5450df20d9c7c3d74524c31788dbc6/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityImpl.java#L476-L482

Usually, we recommend of trying to solve the problem and improve things for everyone instead of just complaining.. but complaining is the first step! so thanks for that 👍

**Comment by paulhh** [comment]
You can also use blame to see who wrote most of the engine.

**Comment by salaboy** [comment]
@paulhh you can use blame for all sort of fun things!
