### ISSUE TITLE
Webservice task cannot be imported to Model workspace

### ISSUE THREAD

**Issue by pplogmann** [Activiti/Activiti#272]
When importing an bpmn20.xml file in activiti-explorer under "Processes -> Model Workspace" information about Webservice tasks are lost.

I noticed this with a webservice task for which the implementation type attribute ("##Webservice") was lost. The initial import seems to happen ok but when "deploy" is selected from the drop dorwn box the error message "One of the attributes 'class', 'delegateExpression', 'type', 'operation', or 'expression' is mandatory on serviceTask." is thrown, because of the validation in  verifyImplementation of ServiceTaskValidator. 

The cause seems to be that the implementation attribute is not included in the JSON which is converted in the activiti-explorer code to the BPMModel an then sent to the engine itself.

When I import the same process using Management->Deployments it works correctly.

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
