### ISSUE TITLE
[DevOps] Separate Maven Central release steps from Docker Hub release steps

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2732]
Split the Bamboo release job into two steps:
- first step build Maven artifacts and publish them to Nexus staging. This step should run on static agent, so that artifacts can be properly signed.
- second step build docker images and push them to Docker hub. This step should run in an elastic agent for Docker Daemon compatibility.

**Comment by Claireedenton** [comment]
Linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3081

**Comment by miguelruizdev** [comment]
Docker side of things can be managed by Jenkins-X, with specific jobs that get triggered once the created tag pattern matches: `7.1.0.*`
It can be configured in Jenkins-X UI:
![image](https://user-images.githubusercontent.com/32025234/57869203-72067300-77fc-11e9-91e7-a7b31a39fefd.png)
The rest can be boiled down to Bamboo config not calling the docker-release scripts: https://github.com/Activiti/activiti-scripts/blob/master/dockerpush-all.sh#L6

**Comment by miguelruizdev** [comment]
**DOCKER MOCK RELEASE VALIDATION:**

- export `MAVEN_ARGS="clean install -DskipTests"`
- export `DOCKER_PUSH=true`
- export `DOCKER_USER=miguelruiz`
- export `RELEASE_VERSION=DOCKER_TEST`
- export `CHECK_VERSIONS=true`
- `PROJECTS=activiti,activiti-cloud,activiti-cloud-modeling,activiti-examples,activiti-cloud-examples,activiti-cloud-modeling-examples ./remove-all.sh`
- `PROJECTS=activiti,activiti-cloud,activiti-cloud-modeling,activiti-examples,activiti-cloud-examples,activiti-cloud-modeling-examples ./clone-all.sh`
- `PROJECTS=activiti,activiti-cloud,activiti-cloud-modeling,activiti-examples,activiti-cloud-examples,activiti-cloud-modeling-examples ./build-all.sh`
- `PROJECTS=activiti-cloud-examples,activiti-cloud-modeling-examples ./dockerpush-all.sh`

Acceptance tests are passing against the environment created off these [docker images](https://cloud.docker.com/u/miguelruiz/repository/docker/miguelruiz/example-runtime-bundle) (the ones tagged as DOCKER_TEST)
This validates the process that the elastic agent should follow in the event of not implementing the changes at the Jenkins-x level before the next release

**Comment by miguelruizdev** [comment]
Conclusion:
In order to work around the fact of an old version of Docker in Bamboo, we will have two cloned jobs with the following configuration, run in the following order:

**Activiti 7 Release:** (original one)

- With no docker related steps (basically the original last one: _./dockerpush-all.sh_)
- No example release (it will be done in the new Docker job)
- No elastic agent (it will keep the original one, _CentOS65_)

**Activiti 7 Docker Release** (as it was validated [here](https://github.com/Activiti/Activiti/issues/2732#issuecomment-499450215))

- No MAVEN_PUSH=true (hence, no _./remove-all.sh_)
- No WhiteSource checks (already covered by the first job)
- Using an elastic agent (since there is no conflict with Docker version)
