### ISSUE TITLE
Activiti explorer module returns an empty list when searching in LDAP for users to assign/reassign the task to.

### ISSUE THREAD

**Issue by marfago** [Activiti/Activiti#275]
The activiti explorer module returns an empty list when searching in LDAP for users to assign/reassign the task to.
It might be due to fact that the value of UserQuery::userFullNameLike contains heading and trailing '%' (as stated in its javadoc) but it is not understood by LDAP (it uses '*' instead which is already declared in spring configuration for LDAP).

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
