### ISSUE TITLE
WildFly 8.1 redeploy app with embedded Activiti 

### ISSUE THREAD

**Issue by ChuGer** [Activiti/Activiti#334]
WildFly 8.1.0.Final redeploy app with embedded Activiti 5.15.1 with Spring (3.2.7) activiti.cfg,xml configuration cause exception:

``` java
org.activiti.engine.ActivitiException: Could not find an implementation of the org.activiti.cdi.spi.ProcessEngineLookup service returning a non-null processEngine.
```

When deploying first time on clean server Activiti-cdi instance starts Ok, but on redeploy 
`protected static boolean isInitialized` variable in class `org.activiti.engine.ProcessEngines` stay equals true, so method 

``` java
  /** obtain a process engine by name.  
   * @param processEngineName is the name of the process engine or null for the default process engine.  */
  public static ProcessEngine getProcessEngine(String processEngineName) {
    if (!isInitialized) {
      init();
    }
    return processEngines.get(processEngineName);
  }
```

not call init method which can add new process engine, so exception thowns.

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
