### ISSUE TITLE
Avoid throwing exception from ModelValidator

### ISSUE THREAD

**Issue by LorenzoDiGiuseppe** [Activiti/Activiti#4225]
`ModelValidator` and its implementors throw exceptions once a validation error has been found.
It would be better to return the list of errors and leave the decision to throw or not to the caller.

**Comment by wojciech-piotrowiak** [comment]
@LorenzoDiGiuseppe Any suggestion which errors should be returned?
Current context:
Validators mostly throw SemanticModelValidationException or SyntacticModelValidationException which cannot be declared in signature in ModelValidator interface - they belong to different project (activiti-cloud-services-modeling-core) . Cannot simply add this project because that would introduce circular dependency.

See a few options:
1. Declare RuntimeException which probably will be too broad
2. Move all exceptions from activiti-cloud-services-modeling-core but I'm afraid of consequences and a lot of changes
3. Move only one exception ModelingException which is parent for other like SemanticModelValidationException/SyntacticModelValidationException. It is doable, tried it locally
4. Create a new interface and map exceptions

Any comment will be helpful, I'm not familiar in this area.
@pmartinezga

**Comment by LorenzoDiGiuseppe** [comment]
@wojciech-piotrowiak this issue is to avoid throwing exceptions in the validation process, so we could replace them with error models. For example, instead of throwing a `SemanticModelValidationException` containing a collection of `ModelValidationError` we could return the collection of `ModelValidationError`.

At the moment, a similar behavior is realized at service level by [`AggregateErrorValidationStrategy`](https://github.com/Activiti/activiti-cloud/blob/645fcfb389f19dc0bb2dd8b2f68deff69846b939/activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/service/utils/AggregateErrorValidationStrategy.java#L28-L91), that catches `SemanticModelValidationException` for extracting and aggregating the list of errors contained in the exceptions.
