### ISSUE TITLE
CRUD  jpa-entity/jpa-entity-list variables through REST

### ISSUE THREAD

**Issue by pdorgambide** [Activiti/Activiti#473]
Hello:
I am trying to manage JPA variables (jpa-entity, jpa-entity-list) throught REST API. The common interface RestVariable made this issue more dificult due that the body of the request is transformed to the value property (LinkedHashMap)  and the RestConverters need to made a roolback to  finally transform to target entity.
I found a case where this is even more complicated, where the entity has properties with   @Enumerated (EnumType.STRING) and  @ElementCollection

I would be very appreciated if you could help me with any sugestion, thanks.

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
