### ISSUE TITLE
Diagram generation in OSGi environnement

### ISSUE THREAD

**Issue by cheleb** [Activiti/Activiti#487]
I was not able to generate diagram when importing a new workflow, base images were not found until a apply this fix https://github.com/Activiti/Activiti/pull/485
Nobody encountered this issue ?

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
