### ISSUE TITLE
JobExecutorMBean#isJobExecutorActivated() logic for 5.17.0

### ISSUE THREAD

**Issue by n0mer** [Activiti/Activiti#538]
@smirzai Please take a look at this code from [JobExecutorMBean.java](https://github.com/Activiti/Activiti/blob/master/modules/activiti-jmx/src/main/java/org/activiti/management/jmx/mbeans/JobExecutorMBean.java)

```
  @ManagedAttribute(description = "check if the job executor is activated")
  public boolean isJobExecutorActivated() {
    return jobExecutor == null || jobExecutor.isActive();
  }
```

When jobExecutor is `null`, then isJobExecutorActivated() always returns `true`.

And in Activiti 5.17.0 jobExecutor is replaced by asyncJobExecutor, so jobExecutor can be `null`.

My point is that this method should return `false` when jobExecutor is `null`.

**Comment by smirzai** [comment]
@n0mer Thank you nikolay
You are absolutely right. 
Here is the fix https://github.com/Activiti/Activiti/pull/540
About the async job executor, it is more than this and should be checked with all aspects.

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
