### ISSUE TITLE
please add @ConditionalOnMissingBean(WebSecurityConfigurerAdapter.class) to RestApiAutoConfiguration.SecurityConfiguration

### ISSUE THREAD

**Issue by n0mer** [Activiti/Activiti#543]
Currently org.activiti.spring.boot.RestApiAutoConfiguration defines SecurityConfiguration the way that requires to set @Order(99) for your custom SecurityConfiguration, if you want to avoid error message 

```
@Order on WebSecurityConfigurers must be unique. Order of 100 was already used, so it cannot be used on org.activiti.spring.boot.RestApiAutoConfiguration$SecurityConfiguration$$EnhancerBySpringCGLIB$$b2f7c0ea@440025ee too.
```

Please add @ConditionalOnMissingBean(WebSecurityConfigurerAdapter.class) to org.activiti.spring.boot.RestApiAutoConfiguration.SecurityConfiguration to allow custom security configuration without necessity to set @Order less than default 100.

**Comment by jbarrez** [comment]
That feels like a good addition indeed.

What do you think @joshlong ?

**Comment by wangsu** [comment]
Same here. Please fix.

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding

**Comment by n0mer** [comment]
@Salaboy sorry, but here is the reference of what "closing issues" means:

![image](https://user-images.githubusercontent.com/1862997/36456874-7902459c-16a7-11e8-9a61-7085344e55ef.png)

**Comment by Salaboy** [comment]
@n0mer exactly, that's why we introduced milestones, the previous team had a chaos here, so we need to do some house cleaning. This issue doesn't apply any more to the activiti/activiti (develop branch )repository for version 7 and for that reason it was closed. We are more than happy to receive collaboration for other branches, but due the limited resources that we have we are focused only on version 7 and Cloud. 

<img width="1013" alt="screen shot 2018-02-21 at 08 53 05" src="https://user-images.githubusercontent.com/271966/36470993-c39a5760-16e4-11e8-9920-9dabb3b6df0f.png">

Thanks for getting in touch and feel free to join our Gitter channel if you want to get involved. It is my personal compromise to keep things under control and making sure that what ever is reported is triaged and dealt with in a proper way

Cheers.
