### ISSUE TITLE
Create new subtask label localization

### ISSUE THREAD

**Issue by admiral-diver** [Activiti/Activiti#561]
Is it possible to move text "Create new subtask:" to messages.properties file

modules/activiti-explorer/src/main/java/org/activiti/explorer/ui/task/SubTaskComponent.java 

Label createSubTaskLabel = new Label("Create new subtask:");

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding
