### ISSUE TITLE
Localization of label "OR" in UploadComponent

### ISSUE THREAD

**Issue by admiral-diver** [Activiti/Activiti#562]
Is it possible to move text "or" to messages.properties file from label

modules/activiti-explorer/src/main/java/org/activiti/explorer/ui/custom/UploadComponent.java 

protected void addOrLabel() {
149     Label orLabel = new Label("or");

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding
