### ISSUE TITLE
databaseTablePrefix cannot be configured with Spring Boot

### ISSUE THREAD

**Issue by bbrouwer** [Activiti/Activiti#622]
I would like to be able to specify `spring.activiti.databaseTablePrefix` in the same way `spring.activiti.databaseSchema` is configured in `application.properties`. 

In my situation, the Activiti tables are in a different Oracle schema than the user's default schema. I want to be able to specify something like `spring.activiti.databaseTablePrefix=ACTIVITI.` (including the period)

**Comment by esarbanis** [comment]
[ProcessEngineConfiguration](http://activiti.org/javadocs/org/activiti/engine/ProcessEngineConfiguration.html) has two properties that might interest you; [tablePrefixIsSchema](http://activiti.org/javadocs/org/activiti/engine/ProcessEngineConfiguration.html#tablePrefixIsSchema) and [databaseTablePrefix.](http://activiti.org/javadocs/org/activiti/engine/ProcessEngineConfiguration.html#databaseTablePrefix)

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding
