### ISSUE TITLE
avoid escaping expression though preceded by \ 

### ISSUE THREAD

**Issue by amitport** [Activiti/Activiti#648]
I'm trying to write code that includes $ in the context of a windows file path. For example:

``` xml
<activiti:field name="X">
    <activiti:expression>c:\folder\${contextVar}</activiti:expression>
</activiti:field>
```

This is evaluated to literal `c:\folder\${contextVar}` since `\${` escapes the expression.

Is there any way I can keep the preceding `\` _and_ evaluate the expression?

**Comment by jbarrez** [comment]
Escape the \ ?

**Comment by amitport** [comment]
un-escape the `\$`
(that is, I want `\${3}` to be evaluated to `\3`, but now it's been evaluated to `\${3}`)

(BTW, tried `\\${3}` but it doesn't work. `${'\\'}${3}` works but is very ugly)

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding
