### ISSUE TITLE
Activiti how to Integration drools6.x

### ISSUE THREAD

**Issue by string2020** [Activiti/Activiti#657]
Activiti 5.18.0  how to Integration drools6.2.0 ?

thinks

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding
