### ISSUE TITLE
Move up ScriptingEngines configuration from ProcessEngineConfigurationImpl to ProcessEngineConfiguration

### ISSUE THREAD

**Issue by seoj** [Activiti/Activiti#671]
I have a use case where I would like to implement and use a customized ScriptingEngines which uses Java security manager wrapped script evaluations. At the moment the only way to override this is to type-cast the ProcessEngineConfiguration into ProcessEngineConfigurationImpl to get access to the getter/setter of the ScriptingEngines.

Unless there is a specific reason the ScriptingEngines does not belong in the parent class, I would like to have this ability to configure it from the parent class.

**Comment by jbarrez** [comment]
The idea is that 'user-friendly' configuration (jdbc props, mail server, etc) lives on ProcessEngineConfiguration and 'advanced' stuff lives in the ProcessEngineConfigurationImpl. All configuration implementations thus extend ProcessEngineConfigurationImpl.

Your use case of changing the ScriptingEngines is definitely in the 'advanced' bucket, so that should remain in the Impl class. 

Why do you need the cast? One easy option is to have your own Configuration that extends from the ProcessEngineConfigurationImpl class.
