### ISSUE TITLE
the form properties test converter must be improved.

### ISSUE THREAD

**Issue by vasiledirla** [Activiti/Activiti#701]

**Comment by jbarrez** [comment]
@vasiledirla : there are two commits on this. Is there anything else still following? Will they end up in another PR?

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
