### ISSUE TITLE
Multi-outgoing sequence flows's behaviour is weird after multi-instance

### ISSUE THREAD

**Issue by AlphaHinex** [Activiti/Activiti#713]
Suppose: a `user task` has two `conditional sequence flow`s, one is to `end event` and the other is to another `user task`.

When the `user task` is a multi-instance activity, the behavior of sequence flows is weird, I created a test case [HERE](https://github.com/AlphaHinex/seed-gradle-java/tree/activiti-multi-outgoing-sequence-flow),  and I think it should be a bug, anyone help?

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
