### ISSUE TITLE
Spring Boot autoconfiguration for beans of persistence interfaces

### ISSUE THREAD

**Issue by jbarrez** [Activiti/Activiti#730]
(v6)

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
