### ISSUE TITLE
ORA-24335 exception on bulk insert of executions

### ISSUE THREAD

**Issue by fiveop** [Activiti/Activiti#733]
Due to a workflow with a lot of parallel execution threads, we encountered an ORA-24335 exception when Activiti tries to bulk insert execution entities.

Answers[[1](http://stackoverflow.com/q/27533517/1271598)][[2](http://stackoverflow.com/q/883706/1271598)] on Stackoverflow to similar problems suggest that the method used in [Execution.xml](https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/Execution.xml) for bulk inserts is not intended for such usage. This probably affects bulk insert statements for other entities as well.

**Comment by jbarrez** [comment]
Bulk inserts can be enabled/disabled by setting the 'bulkInsertEnabled' to false (on the process engine config).

You can limit the size of the the bulk insert by setting the 'maxNrOfStatementsInBulkInsert', which problem would solve the problem here. Although if 1000 is the limit, it probably need to be quite a small number...

**Comment by ossema95** [comment]
Hello @jbarrez,

where i can manage these properties ?
im currently using the Standalone process configuration (Activiti6.0) but i cant find the service to disable/enable the bluk insert:


![New Bitmap Image](https://user-images.githubusercontent.com/56094895/124780835-d3d54a00-df3a-11eb-9ad3-f920888c96c6.jpeg)
