### ISSUE TITLE
Simple asynchronous task never finish in history

### ISSUE THREAD

**Issue by SergioModulusData** [Activiti/Activiti#736]
I'm testing out asynchronous task for reply and different uses case we have. I had a problem finding the end time on my instance so I decided to make a simple process to check how Activiti works with asynchronous task.

See this project here : https://github.com/Log10Solutions/UnitTestSimpleAsync

The test I made works if there is no async in the whole process or the process start is mark as async. If the script task is asynchronous than the print is not done in the console and the task is not updated in the history with an end time.

Is there something missing in my test ?

**Comment by balsarori** [comment]
In the processEngineConfiguration you need to set jobExecutorActivate and asyncExecutorActivate to true as follows

```
<property name="jobExecutorActivate" value="true" />
<property name="asyncExecutorActivate" value="true" />
```

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
