### ISSUE TITLE
exception handling anti-pattern in AtomicOperationProcessEnd

### ISSUE THREAD

**Issue by tyrcho** [Activiti/Activiti#739]
When several subprocesses are nested and an exception is thrown, it is logged at each subprocess level. This means a huge stack trace logged several times.

This is the responsible line : 
https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/java/org/activiti/engine/impl/pvm/runtime/AtomicOperationProcessEnd.java#L53

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
