### ISSUE TITLE
Should move away from Spring...

### ISSUE THREAD

**Issue by renfeng** [Activiti/Activiti#744]
To make it lighter, and less intrusive.

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
