### ISSUE TITLE
Loop with BpmnError - SQL exception on saving variables

### ISSUE THREAD

**Issue by SergioModulusData** [Activiti/Activiti#746]
I have a simple test that triggers a SQLException when trying to handle error with an event sub process. The loop is not sequential.

https://github.com/Log10Solutions/loop-error-activiti-test

The test will always triggers a SQL exception when saving this 

```
 09:19:13,397 [main] DEBUG org.activiti.engine.impl.persistence.entity.VariableInstanceEntity.bulkInsertVariableInstance  - ==>  Preparing: INSERT INTO ACT_RU_VARIABLE (ID_, REV_, TYPE_, NAME_, PROC_INST_ID_, EXECUTION_ID_, TASK_ID_, BYTEARRAY_ID_, DOUBLE_, LONG_ , TEXT_, TEXT2_) VALUES (?, 1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) , (?, 1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
09:19:13,397 [main] DEBUG org.activiti.engine.impl.persistence.entity.VariableInstanceEntity.bulkInsertVariableInstance  - ==> Parameters: 22(String), integer(String), loopCounter(String), 5(String), 15(String), null, null, null, 1(Long), 1(String), null, 27(String), integer(String), loopCounter(String), 5(String), 17(String), null, null, null, 2(Long), 2(String), null
```

Creates this exception

```
### Error updating database.  Cause: org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "ACT_FK_VAR_EXE: PUBLIC.ACT_RU_VARIABLE FOREIGN KEY(EXECUTION_ID_) REFERENCES PUBLIC.ACT_RU_EXECUTION(ID_) 
```

Is it possible that my test is missing something to work ?

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
