### ISSUE TITLE
Multi instance task fails when clearing the collection

### ISSUE THREAD

**Issue by romainguay** [Activiti/Activiti#748]
Hi,

I am facing a new issue with multi instance tasks which are failing with PvmException("already taking a transition") when the collection over which we are looping becomes empty at any point after looping.

I have this scenario for example if the collection need to get filtered after looping. If it happens to become empty, then the error occurs.

I am using Activiti 5.19.0 and I have created a unit test at https://github.com/Log10Solutions/clear-collection-test

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
