### ISSUE TITLE
ACT_RU_JOB table on MySQL

### ISSUE THREAD

**Issue by ycoulon** [Activiti/Activiti#750]
Working on Alfresco 5.0.c I faced an issue with the ACT_RU_JOB table on MySQL.

This issue is linked to the column "DUEDATE_" that has a "TIMESTAMP" datatype and occurs when we want to set a "DUEDATE_" that is greater than '2038-01-19 03:14:07.999999'.

According to MySQL valid range for "TIMESTAMP" field is '1970-01-01 00:00:01.000000' to '2038-01-19 03:14:07.999999'.

Maybe this column should use a DATETIME type instead of TIMESTAMP.

**Comment by Lywei** [comment]
have you finished it ?

**Comment by Lywei** [comment]
i want  to motify the time of ACT_RU_JOB table,how to do,pls?

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
