### ISSUE TITLE
Enhancement Request for Activiti History Engine

### ISSUE THREAD

**Issue by SampathK** [Activiti/Activiti#766]
We have multiple Workflow defined to perform difference Business Processing Activiti. However We want to track History for only Specific Set Activiti. 

Current Activiti provides Enabling and Disabling History at Global Level. This Results in a Lot of Insertion on History Tables, which in turn impacts performance, maintenance through purging script.
We have daily Millions of Entries filling up table space.

Following Enhancement I am proposing

1) Disable/Enable History at Workflow Level During Deployment time
2) Disable/Enable History at Process Instance ID level
3) Provide a Plugin Implementation to add customized History Logging
4) Provide a option to Purge History after Specific Period again give a option to define at workflow level

Currently I am observing History as a bottleneck for performance because of non availability of above features. Let me know your thoughts regarding this ?

Regards,
Sakumar

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
