### ISSUE TITLE
Activiti Explorer Error Using Existing SQL Server 2012 DB Containing Table Names Beginning with 'ACT'

### ISSUE THREAD

**Issue by JasonD5150** [Activiti/Activiti#786]
When deploying the Activiti DB to an existing SQL Server 2012 DB, the org.activiti.engine.impl.persistence.entity.TableDataManager#getTablesPresentInDatabase method selects not only the 'ACT_%' tables but any table name starting with 'ACT' such as 'ACTIVITY', 'ACTUAL_COUNTS', etc.

It seems for SQL Server, the '_' character should be escaped in the same manner as Oracle ala:

```
        if ("oracle".equals(getDbSqlSession().getDbSqlSessionFactory().getDatabaseType()) ||
              "mssql".equals(getDbSqlSession().getDbSqlSessionFactory().getDatabaseType())) {
          tableNameFilter = databaseTablePrefix+"ACT" + databaseMetaData.getSearchStringEscape() + "_%";
        }
```

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
