### ISSUE TITLE
5.19 explorer war set wrong version number in database

### ISSUE THREAD

**Issue by mohammadabdellatif** [Activiti/Activiti#841]
When you run the explorer war and the database get created, the version of activiti in ACT_GE_PROPERTY would have the value of 5.20.0.1 instead of 5.19.
I took a look into the scripts file in activiti-engine jar and found that the insert statement is:
insert into ACT_GE_PROPERTY
values ('schema.version', '5.20.0.1', 1);

while you create a new maven project and have the dependency as below:
<dependency>
      <groupId>org.activiti</groupId>
      <artifactId>activiti-engine</artifactId>
      <version>5.19.0</version>
    </dependency>

I took a look into the jar downloaded by maven and I found that it inserts the correct version number into database which matches the version number of the library:
insert into ACT_GE_PROPERTY
values ('schema.version', '5.18.0.1', 1);

**Comment by mohammadabdellatif** [comment]
After taking another look I found that you need to include the same exact version that exists in the explorer war which is 5.19.0.2 instead of using 5.19.0

**Comment by tijsrademakers** [comment]
Hi, the database version number is an independent number from the Engine version. We need it to be de-coupled so we can release snapshot versions of the Engine without worrying about backwards compatibility. When we released 5.19.0.2 the database schema changes were already underway for the next 5.20.0 version of the Engine, so that's why you see 5.20.0.1 there. When we'll release 5.20.0 the version number will be in-sync again.
