### ISSUE TITLE
JSON converter is AL 2.0 licensed but has LGPL 2.0 dependency

### ISSUE THREAD

**Issue by ilgrosso** [Activiti/Activiti#842]
JSON converter is released under AL 2.0 (as the whole Activiti platform) but [depends](https://github.com/Activiti/Activiti/blob/master/modules/activiti-json-converter/pom.xml#L127-L128) on javaGeom, which is released under LGPL 2.0, according to https://sourceforge.net/projects/geom-java/.

**Comment by Salaboy** [comment]
@ilgrosso hi there, thanks for reporting this. We will probably remove this dependency in the future (or make it optional), but for now I'm closing this issue, because we are not an official Apache project we are not forced to guarantee that all our dependencies and transitive dependencies are ASL compatible.
We are currently splitting the platform, so even the JSON converter is something that you can exclude if you don't want to include an LGPL library in your environment. 
It sounds like a great community contribution, to find an alternative library for GeomJava, so if you want to contribute that will be great. 

You make a good point here, and we will try to be as aligned with Apache Licensed libraries (as practical) as possible.
