### ISSUE TITLE
Activiti6: Invalid reference in 'bpmnElement' attribute, sequenceFlow ... not found

### ISSUE THREAD

**Issue by reva** [Activiti/Activiti#865]
Reopening https://github.com/Activiti/Activiti/issues/801. Could not find the unit tests @yvoswillens was referring. (Could not find ANY unit tests testing BpmnParse, really)

This is a bug in my opinion. Right now I get a log statement about missing sequence flows for every process that I deploy. Working on a pull request.

**Comment by kartheepanmirra** [comment]
Yes the defect is due to the fact that the sequnceFlows maps in BpmnParse.java BpmnParse.sequenceFlows used to get added with values in the SequenceFlowParseHandler.executeParse at line number 55  bpmnParse.getSequenceFlows().put(sequenceFlow.getId(), transition); in the older version 5.19.2.


The current beta version code has the following syntax

protected void executeParse(BpmnParse bpmnParse, SequenceFlow sequenceFlow) {
    org.activiti.bpmn.model.Process process = bpmnParse.getCurrentProcess();
    sequenceFlow.setSourceFlowElement(process.getFlowElement(sequenceFlow.getSourceRef(), true));
    sequenceFlow.setTargetFlowElement(process.getFlowElement(sequenceFlow.getTargetRef(), true));
  }

**Comment by reva** [comment]
The PR is already there. Another simple fix, really. Corresponding jira issue: https://activiti.atlassian.net/browse/ACT-4142

**Comment by tijsrademakers** [comment]
Fixed
