### ISSUE TITLE
activiti 5.19: Saving model fails on IE10

### ISSUE THREAD

**Issue by Jaroslav23** [Activiti/Activiti#869]
Attempt to save model in activiti-explorer in IE10 fails with:

Element type "path" must be followed by either attribute specifications, ">" or "/>".
        at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:13
6)        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:15
6)        at org.activiti.rest.editor.model.ModelSaveRestResource.saveModel(ModelSaveRestResource.java
:82)        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

the reason seems to be that in the SVG received from client
instead of <path marker-end="url(#sid-B3872D6A-E740-41BA-A797-F9A25ECC109Bend)"
we see <path marker-end="url("#sid-DB178223-49E1-4269-A8CE-E0A14EB5D122end")"

when debugging with IE you can see the path attribute is set to correct value, but IE internally uses "url(\"#sid-DB178223-49E1-4269-A8CE-E0A14EB5D122end\")". The extra \ seems to get lost somewhere when sending data to server. Another option is IE just displays extra \ in the debugger but it isn't there

**Comment by lizige** [comment]
wo also have this issues

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
