### ISSUE TITLE
implement 'restApiMapping'

### ISSUE THREAD

**Issue by amitport** [Activiti/Activiti#871]
[this](https://github.com/Activiti/Activiti/blob/769b3372fce3ec7d233b122510f83e57405c5426/modules/activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter-basic/src/main/java/org/activiti/spring/boot/ActivitiProperties.java#L49) looks like a preparation for allowing activiti-rest to be loaded with spring-boot and mapped to a specific prefix url. Unfortunately, it does not seem to be used anywhere.

Is there any chance this functionality could be implemented?

thanks

**Comment by ziben** [comment]
I want this future!

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
