### ISSUE TITLE
Activiti Explorer with Spring Boot

### ISSUE THREAD

**Issue by sankarbalu** [Activiti/Activiti#877]
I am developing a spring boot application that runs the activiti workflow engine in an embedded Tomcat container. The database used in Oracle. I would to know whether activiti explorer can be used to view the processes handled through his spring boot application? If yes, are there any sample configurations for reference?

**Comment by daisuke-yoshimoto** [comment]
Activiti explorer cannot be used through spring boot.
https://forums.activiti.org/content/activiti-explorer-and-springboot

Because activiti explorer project isn't jar project but war project, you cannot use activiti explorer project through spring boot.
https://github.com/Activiti/Activiti/tree/master/modules/activiti-webapp-explorer2

You can use activiti engine or activiti rest with spring boot.
* Guide
https://spring.io/blog/2015/03/08/getting-started-with-activiti-and-spring-boot

* Sample project
https://github.com/jbarrez/spring-boot-with-activiti-example

Otherwise, if you will use activiti explorer only in an embedded Tomcat container, you can use.

**Comment by yalmuhaidib** [comment]
I think this will be a wanted feature later, I already asked something similar #860

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
