### ISSUE TITLE
messages_ar.properties in arabic language

### ISSUE THREAD

**Issue by asaadhoussam** [Activiti/Activiti#882]
After you create a file  messages.properties in arabic language, It did not appear in the Arabic language!
what should I do?

**Comment by faizal-manan** [comment]
this is not activiti issue
[http://stackoverflow.com/questions/2183245/internationalization-in-a-website](read here)
[https://www.google.com/search?q=java+internationalization+arabic&oq=java+internationalization+arabic&aqs=chrome..69i57j69i64.5648j0j7&sourceid=chrome&ie=UTF-8#q=java+internationalization+arabic+example+code](find in here)

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
