### ISSUE TITLE
Too many asynchronous continuations deleted when end event reached

### ISSUE THREAD

**Issue by jakobtonn** [Activiti/Activiti#951]
I have noticed that in Activiti 5.19 -5.21, when you execute a process that has a parallel gateway splitting into several paths, with each path leading to an individual end event, and asynchronous activities on the parallel paths, the activities that have not been executed yet are never executed after one of the paths reaches its end event. From my understanding of BPMN modelling, such a process should behave the same way as joining all parallel paths before a single end event, which would mean that all activities are executed until all tokens reach an end event. From my analysis, the problem seems to be that Activiti deletes all asynchronous continuations of a process once one end event is reached, even if the process should continue to execute other paths.

I have created a JIRA issue for this problem with a more detailled explanation, example process and unit test here: https://activiti.atlassian.net/browse/ACT-4192. As (at least for me) Activiti's current behaviour differs from what the BPMN standard defines, this is (imo) a rather critical issue.

**Comment by jbarrez** [comment]
Yes, that is indeed the behaviour: both paths will try to update the same execution concurrently. In this case, you need to set both async steps to 'exclusive', by adding the activiti:exclusive="true" attribute. This will make sure both steps do not conflict with each other.

**Comment by jakobtonn** [comment]
I think I have to explain a bit further...  in the process I added to the JIRA issue, even with both parallel asynchronous tasks set to exclusive, the entry for the second task (the one still waiting to be executed) in the job table gets removed when the first asynchronous task is complete and the subsequent end event is reached.

**Comment by jbarrez** [comment]
Okay, I see what you mean now. That is indeed not correct behaviour, yet not that easy to fix with the v5 architecture (quite some hacking would be required which would not be good for performance). The problem is not the deletion of the jobs, but rather that Activiti v5 tries to optimise executions and folds the two executions back to one in this particular case.

The good news is that it runs as expected on v6 (the core architecture is different there). As such, I'd advise to use the workaround (use an explicit joining parallel gateway) for now, with V6 is around the corner.

**Comment by jakobtonn** [comment]
Thanks for this information, I will avoid this modelling pattern then and use appropriate workarounds instead until we can migrate to Activiti 6. Unfortunately our real-world processes are a bit more complicated than the simple example, but knowing what to avoid helps a lot.
