### ISSUE TITLE
"How can I become a contributor" hyperlink at activiti.org become much outdated

### ISSUE THREAD

**Issue by olegchir** [Activiti/Activiti#985]
All Codehaus services have been terminated, therefore hyperlink to the wiki points to nothing

Steps to reproduce:

- Navigate to: http://activiti.org/faq.html#HowToBecomeAContributor

- Use this hyperlink: "See wiki page How to become a contributor?"
(http://docs.codehaus.org/pages/viewpage.action?pageId=163872771)

Actual result:
Codehaus termination page: https://www.codehaus.org/termination/?pageId=163872771

Desired:
Wiki page

**Comment by dbmalkovsky** [comment]
This issue is also reported in this forum [post](https://forums.activiti.org/content/contribution-hana-db-support).

FWIW, I found an old version of the page on at web.archive.org from May, 2015.  I've tried to replicate the text with newer links here:



# How to become a contributor?

## Many forms of contributions

There are very different ways how you can contribute and some of them are very easy.  We even consider just complaining a good contribution ;-)   As it's always good to know where we can improve.  

If you indicate a constructive proposal of how we could improve it, even better.  If you actually create a pull request and a unit test as part of a jira issue, that's even better.

If you have an idea for a code contribution, just follow the steps below.

1.   Signing a contributor agreement

  In order for us to be able to accept your contributions, we need you to sign a contributor agreement.    Download, print, sign, scan an [individual contributor agreement](http://activiti.org/Alfresco_Contribution_Agreement.pdf).  Then send the signed scan to   tijs.rademakers AT alfresco dot com.

1.  Guidelines

  The 2 most important communication channels with the team are the [developer forum](https://web.archive.org/web/20150504021402/http://forums.activiti.org/en/viewforum.php?f=4) and our [jira](https://activiti.atlassian.net/) issues repository.

Create an issue in our jira issues repository or comment on an existing issue for the work that you plan to commit.  Explain what you plan to do and ask for feedback.

You can propose contributions by forking the activiti repository in your personal github space and  then creating a [pull request](https://help.github.com/articles/using-pull-requests).

Check out this blog [post](http://www.jorambarrez.be/blog/2012/09/24/how-to-write-a-unit-test/) It explains how to write a unit test for a contribution.  When you supply a unit test, it greatly enhances the chance of your contributions to be accepted.

Before you submit a pull request, always run **mvn -Pcheck clean install** and ensure it runs fine.  It's good if you indicate that you've ran this successfully.

**Comment by dbmalkovsky** [comment]
This information has been added to the `[wiki](https://github.com/Activiti/Activiti/wiki/How-to-become-a-contributor%3F)`

The FAQ has not been updated yet.

**Comment by olegchir** [comment]
Where's sources of FAQ page are located? Maybe we should create PR for changing this

**Comment by tijsrademakers** [comment]
Thanks guys, I've updated the FAQ based on your findings (it will take 30 min or so, before the changes will be online).
