### ISSUE TITLE
Roadmap for v6

### ISSUE THREAD

**Issue by olegchir** [Activiti/Activiti#991]
Is there somewhere a roadmap for version 6?

I see only notes
(https://github.com/Activiti/Activiti/wiki/Activiti-V6-notes)

and this page with "Roadmap moved to somewhere else" 
(http://www.activiti.org/roadmap.html)

Notes are good but has not been updated since May

Major question is in ETA for v6 and what should be added/fixed/changed before that. 
At least just to know how to allocate our time and to assess the risks.

@jbarrez @tijsrademakers

**Comment by tijsrademakers** [comment]
We are feature complete for the Activiti Engine for v6, so we only have bug fixes from the community before we can release the final version. The Activiti 6 UI logic has changed quite a bit since beta 2 and that's what's remaining before we can release a beta 3 and hopefully shortly after that a release candidate.

**Comment by olegchir** [comment]
Please don't close this ticket for day or two, I should escalate this info to someone from our team who can make decisions about release planning. I'll close by myself it asap

**Comment by olegchir** [comment]
@tijsrademakers 
Thank you for your cooperation! 
Right now we're working on "activiti6" branch
